---
title: "BT_sections"
author: "Ben Travis"
date: "2/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if (!require("tidyverse")) install.packages("tidyverse"); library(tidyverse)
if (!require("readr")) install.packages("readr"); library(readr)
if (!require("dplyr")) install.packages("dplyr"); library(dplyr)
```

```{r}
library(readr)
Covid_19<-read_csv("Data/Provisional_COVID-19_Deaths_by_Sex_and_Age.csv")
str(Covid_19)
getwd()
```

## Code for Ranking net Deaths by State

```{r}
library(dplyr)

#Looking at original dataset and ensuring State = coded as a factor
Covid_19$State<-as_factor(Covid_19$State)
nlevels(Covid_19$State)
summary(Covid_19$State)
#54 states, need to remove non-states

#Filter functions (one to be used as an example of != and one to be used as an example of ==)
Covid_19.S<-filter(Covid_19, State != "United States" & State != "District of Columbia" & State != "New York City" & State != "Puerto Rico")
Covid_19.S.T.X.A<-filter(Covid_19.S, Group == "By Total" & Sex == "All Sexes" & `Age Group` == "All Ages")

#ensuring filter process worked
table(Covid_19.S.T.X.A$State)
nlevels(Covid_19.S.T.X.A$State)

#data display
arrange(Covid_19.S.T.X.A,desc(`COVID-19 Deaths`))
```



library(dplyr)
Covid_19.AT.S4.B %>%
  mutate(EC = State %in% c("Alabama", "New York")) -> Covid_19.AT.S4.B


## Code for Visualizing "do older people have higher death rates than younger people?"
```{r}
library(dplyr)
Covid_19$`Age Group`<-as.factor(Covid_19$`Age Group`)
#age group = factor

Covid_19 %>%
  filter(State == "United States") %>%
  filter(Sex == "All Sexes") %>%
  filter(Group == "By Total") %>%
  summarize(State, Sex,`Age Group`, `COVID-19 Deaths`) -> Covid_19.Deaths.by.Age
#Isolates total Covid deaths in the country regardless of sex in its own Data set (filter and sumarize function example)

table(Covid_19.Deaths.by.Age$`Age Group`)
```

```{r}
Covid_19.Deaths.by.Age %>%
  filter(`Age Group` != "0-17 years" & `Age Group` != "All Ages" & `Age Group` != "55-64 years") ->Covid_19.Deaths.by.Age
#removing 0-17 years and All Ages and 55 - 64 years

Covid_19.Deaths.by.Age$`Age Group`<-recode_factor(Covid_19.Deaths.by.Age$`Age Group`, `Under 1 year` = "0-1 years", `1-4 years` = "01-4 years", `5-14 years` = "05-14 years")
 #renaming under 1 year to 0-1 year
table(Covid_19.Deaths.by.Age$`Age Group`)
#validating change
```
```{r}
library(ggplot2)
plot_Ds.by.Age<-ggplot(data=Covid_19.Deaths.by.Age, aes(x=`Age Group`, y=`COVID-19 Deaths`)) +
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 50, vjust = 0.7, hjust=0.5))
plot_Ds.by.Age
#plotting the data

```



## Checking if the total deals match for each time division (by month, by year, total)

```{r}
sum(Covid_19.S.T.X.A$`COVID-19 Deaths`)
# All US total deaths (from the 50 states) from "by total" time catagory

Covid_19.S %>%
  filter(Sex == "All Sexes") %>%
  filter(Group == "By Year") %>%
  filter(`Age Group` == "All Ages") %>%
  summarize(Group, State, Sex,`Age Group`, `COVID-19 Deaths`) ->Covid_19.Deaths.byY
sum(Covid_19.Deaths.byY$`COVID-19 Deaths`)
#all US total deaths (from the 50 states) from "By Year" time category

Covid_19.S %>%
  filter(Sex == "All Sexes") %>%
  filter(Group == "By Month") %>%
  filter(`Age Group` == "All Ages") %>%
  summarize(Group, State, Sex,`Age Group`, `COVID-19 Deaths`) ->Covid_19.Deaths.byM
sum(Covid_19.Deaths.byM$`COVID-19 Deaths`, na.rm = TRUE)
#all US total deaths (from the 50 states) from "By Month" time catagory


```









