% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{Group Project 3}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Biology 368/664 Bucknell University}
\author{Prof.~Ken Field}
\date{9 Feb 2022}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Group Project 3},
  pdfauthor={Prof.~Ken Field},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

Dataset we are using:
\url{https://data.cdc.gov/NCHS/Provisional-COVID-19-Deaths-by-Sex-and-Age/9bhg-hcku/data}

\#INTRODUCTION TO EPIDEMIOLOGY:

Epidemiology is the ``study of distribution and determinants of health
related states among specified populations and the application of that
study to control health problems'' (A Dictionary of Epidemiology). The
purpose of epidemiology in public health practice is to: (1) discover
and analyze agents that affect heath, (2) determine causes of illness,
disability, and death, (3) identify populations at risk, and (4) develop
effective programs and services to to improve population health. Many
epidemiologists solve health problems through a formal scientific
approach that includes data collection, assessment, hypothesis testing,
and action.

The employment of epidemiology has been notably publicized by the
COVID-19 epidemic. As many people have been impacted by the virus in
various capacities, this has sparked curiosity into how professionals
identify, measure, and represent the epidemiology of such infections. In
this R tutorial, we will assume the role of an epidemiologist and
conduct a formal scientific method using a COVID-19 dataset provided by
the Centers for Disease Control (CDC).

At the conclusion of this project, the following should be accomplished:
1. Relate epidemiology data collection to data science/analysis 2. Carry
out the scientific method a. Perform an exploration of the dataset using
R b. Perform basic data analysis using R c.~Draw conclusions from the
analysis

\#INTRODUCTION TO R:

For many epidemiologists, the use of R Studio can be an effective
program used to analyze collected data. As we are student
epidemiologists, the aim of this tutorial and project is to introduce
the application of data analysis in R. Using R studio, however, may be a
daunting task for those with limited experience with computer coding.
This basic introduction to R serves to help alleviate such stress.
Throughout the project, we will slowly add to a toolbox of coding
techniques.

First, it is important to understand the different types of files you
can use in R Studio. Today, we will go over R Markdown and R Notebook.

R Markdown files allow you to include text with embedded R code chunks.
When the document is knitted and finalized you will be able to see the
text, code chunks, and the output of those embedded chunks. This is a
great tool for authors because it saves the time of copying and pasting
graphs or tables into a report and aids in reproducibility. Using R
Markdown allows others to see exactly what was done to produce the
figures.

R Notebook is quite similar to R Markdown except in a notebook only one
line is sent at a time. In contrast, R Markdown executes the entire code
chunk at once. Another large difference is when a R Notebook file is
rendered no code is re-run, only the code that has already been run will
be presented in produced document. Whereas when an R Markdown file is
rendered all code chunks are re-run and it will not allow you to convert
it to a document if there is an error in a code chunk.

\#\#R Studio Basics:

Code chunks can be created in the RMD file. This is where desired
functions of analysis can be performed. The creation of a code chuck can
be completed via clicking the green square ``C'' in the above toolbar,
or by using the keyboard shortcut of cmd+option+I on macOS.

Additionally, one can transform their markdown file into a HTML, PDF, or
word document. This is referred to as ``rendering'' and can be done by
clicking on the Knit button up in the R Studio toolbar. When you press
Knit, it will run all of your code and create an output. If you want to
omit the code but include the results of a chunk in your final document
use echo = FALSE. If you want to omit the code and the results form the
document use include = FALSE, as shown below.

This code helps set up the R markdown document to make a nice clean html
file for sharing. Click the green triangle to run the code chunk.

To create headers in the text outside of the code chunk, once can place
a single hash tag (\#) in front of the text. For subheaders, use two
hash tags (\#\#). The following additions can be used to improve upon
text: 1.To italicized text, surround the text with asterisk (*). 2.To
bold text, surround it with two asterisks (**) 3.To create a list, place
on asterisk (*) in front of each line.

These additions may appear throughout the following project, but would
be more apparent if the RMD became knitted. The text will not appear
italicized or bolded etc when you run your code, however, when the
document has been finalized, the text will be altered accordingly.

Packages are collections of R functions, data, and compiled code which
are stored in the library. The ``System Library'' can be found under the
packages tab. The library will have checked boxes next to packages that
are loaded into the current project. Packages can either be manually
added (via installation tab in ``Packages'') or coded in via a code
chunk. For simplicity, all packages should be installed in the first
code chunk, however, if a package is needed later in the project, it can
always be added. A general list of packages one may want to always start
off with include \emph{dplyr}, \emph{ggplot2}, \emph{readr}, which is
consistent of the tidyverse library (and should be added last in a code
chuck).

Uses of the tidyverse library: 1.dplyr: Summarizes data quick and
efficiently. 2.ggplot2: Data visualization 3.readr: Used read\_csv()

In the example below, other packages are loaded into the project. These
packages beyond tidyverse are: 1.Cowplot: Additional package to ggplot;
includes features to make publish ready figures 2.Car: Used for
statistical analysis; specifically linear models 3.Stat2Data: Used to
organize data in dataframe

Finally, the require function is used to ensure we actually get the
package we want. If R Studio is unable to receive it, the code will come
back with an error or FALSE.

Normally the R setup chunk can be included in the load libraries chunk,
but they have been separated today to allow for proper explanation.

\#\#Loading in Datasets:

Here we will walk through how to load your data set in, and what each
part of the code means. First on the left you put the name you want for
your data set. 1. \textless{} - This assigns the data frame to a
variable 2. read\_csv reads the data into RStudio as a data frame 3.
Within the parentheses is how you tell it where to find your data 4. The
period (.) indicates that the data is located one folder or click away
from your RMD file

Click this green arrow to run a chunk of code that produces output. If
this code is successful, you should see ``Covid\_19'' appear as a
dataframe in the top right box of the R Studio interface under the
``Environment'' tab.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Covid\_19 }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"./Data/Provisional\_COVID{-}19\_Deaths\_by\_Sex\_and\_Age.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 82620 Columns: 16
\end{verbatim}

\begin{verbatim}
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr (8): Data As Of, Start Date, End Date, Group, State, Sex, Age Group, Foo...
## dbl (2): Year, Month
\end{verbatim}

\begin{verbatim}
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

Click on the ``Covid\_19'' dataset in the Environment tab and it will
pull up a tab for you to view it. Before you start exploring your
dataset, one should check to see if any column names have spaces in
them. As R Studio has trouble reading spaces, it is easiest to rename
these columns at the beginning of a project.

In the code chunk below, the spaces in the column names are changed in
incorporate periods (.). This will make the data much easier to work
with. After running the code chunk, check your dataframe to assure that
the change was successful.

The structure of this function is as follows:
names(dataframe)\textless-make.names(names(dataframe))

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(Covid\_19) }\OtherTok{\textless{}{-}} \FunctionTok{make.names}\NormalTok{(}\FunctionTok{names}\NormalTok{(Covid\_19))}
\end{Highlighting}
\end{Shaded}

\#EXPLORATION OF DATASET:

When a dataset is uploaded, there is an informal checklist to complete
before visualization and analysis. One should become familiar with the
elements in the dataset. The dataframe provides epidemiological data
that is inclusive of: 1.Data ``as of'' date 2.Start dates of data
collection 3.End dates of data collection 4.Grouped data by month, year,
or total 5.Year of collected data (if applicable) 6.Month of data
collection (if applicable) 7.State of data collection, or the entire
United States 8.Sex divided into male, female, or total 9.Varied age
groups or total collections 10.COVID-19 Deaths 11.Total Deaths
12.Pneumonia Deaths 13.Pneumonia Deaths and COVID-19 Deaths 14.Influenza
Deaths 15.Pneumonia, Influenza, or COVID-19 Deaths 16.Footnotes

These variables are all divided into their own column. Just by initially
looking through these variables, one can notice some complexities that
should be noted. This dataframe includes both summed total data and
individual unit data. Thus, both broad and narrow analysis can be made
using the dataset. For example, could could compare total deaths in the
United States by age group, or one could look at total deaths by month,
sex, and age group in a particular state. Caution should be used,
however, when filtering the data when conducting an analysis to answer a
particular question. Finally, for this dataframe, there are 82620
observations that can be inferred as individual points of collection.

Key functions for visualizing data in R studio include: 1. \&: Narrows
search between dataframe and columns. 2. \textasciitilde: Comparison of
variables that are ``dependent on'' one another; defines relationship
between independent and dependent variable.

\#\#Formulating a Question:

Once the variables of the dataframe have been assessed, one should
formulate a question. Assuming this dataframe was given to an
epidemiologist, they may be particularity interested in the time, state,
sex, and COVID-19 Death variables. Formulating a question at the
beginning of data analysis can limit extraneous paths taken with a large
dataset. A precise question and/or hypothesis can eliminate unnecessary
variables from the subsequential analysis.

The questions we are interested in for this R tutorial: 1. Do males or
females have more COVID-19 deaths per month? 2. Does west or east coast
have more COVID-19 deaths? 3. Do older people have higher COVID-19
deaths?

The hypothesis(s) we are interested in for this R tutorial are: 1. We
hypothesize that there will be no difference in COVID-19 deaths between
the to genders. 2. We hypothesize that there will be more COVID-19
deaths reported for the East coast. 3. We hypothesize that there will be
more COVID-19 deaths reported for older individuals

\#\#Read Data:

The next step in exploratory data analysis is to read in a portion of
data. The purpose of this task is to determine if the data is ``messy''
and should be ``cleaned''. Messy data will often times not be orderly,
have missing values, and is not suitable for immediate data
visualization. As the data provided was from the CDC, we can expect
relatively ``clean'' data.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readr)}
\FunctionTok{summary}\NormalTok{(Covid\_19)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Data.As.Of         Start.Date          End.Date            Group          
##  Length:82620       Length:82620       Length:82620       Length:82620      
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##       Year          Month           State               Sex           
##  Min.   :2020   Min.   : 1.000   Length:82620       Length:82620      
##  1st Qu.:2020   1st Qu.: 3.000   Class :character   Class :character  
##  Median :2021   Median : 6.000   Mode  :character   Mode  :character  
##  Mean   :2021   Mean   : 6.115                                        
##  3rd Qu.:2021   3rd Qu.: 9.000                                        
##  Max.   :2022   Max.   :12.000                                        
##  NA's   :2754   NA's   :11016                                         
##   Age.Group         COVID.19.Deaths     Total.Deaths     Pneumonia.Deaths  
##  Length:82620       Min.   :     0.0   Min.   :      0   Min.   :     0.0  
##  Class :character   1st Qu.:     0.0   1st Qu.:     39   1st Qu.:     0.0  
##  Mode  :character   Median :    11.0   Median :    147   Median :    18.0  
##                     Mean   :   391.7   Mean   :   2741   Mean   :   371.1  
##                     3rd Qu.:    72.0   3rd Qu.:    660   3rd Qu.:    84.0  
##                     Max.   :898699.0   Max.   :7070005   Max.   :798605.0  
##                     NA's   :20551      NA's   :12132     NA's   :24504     
##  Pneumonia.and.COVID.19.Deaths Influenza.Deaths   
##  Min.   :     0.0              Min.   :    0.000  
##  1st Qu.:     0.0              1st Qu.:    0.000  
##  Median :     0.0              Median :    0.000  
##  Mean   :   204.2              Mean   :    3.732  
##  3rd Qu.:    36.0              3rd Qu.:    0.000  
##  Max.   :466948.0              Max.   :10229.000  
##  NA's   :20410                 NA's   :13510      
##  Pneumonia..Influenza..or.COVID.19.Deaths   Footnote        
##  Min.   :      0.0                        Length:82620      
##  1st Qu.:      0.0                        Class :character  
##  Median :     26.0                        Mode  :character  
##  Mean   :    567.5                                          
##  3rd Qu.:    125.0                                          
##  Max.   :1239112.0                                          
##  NA's   :23713
\end{verbatim}

The readr package is used here because it can read and analyze large
dataframes fast. Also note the library notation of readr. This operation
loads/attaches packages and stores them in the ``System Library''
located under the Packages tab. This is an example of reading in a
package into a code chuck, but again, this package was already loaded at
the beginning of the project.

The summary of the ``Covid\_19'' dataframe can be performed to get a
general idea of what type of data is included (character, integer, and
numeric variables) and it also preforms a basic analysis of the numeric
data by providing quartile ranges.

At the beginning of this project, we removed the spaces in the column
names. Should they be changed at any point, the rename function can be
used. The general structure of the rename function is as follows:
dataframe (can make new or use original)\textless-rename(dataframe, new
column name=``column with spaces/Old name'')

Run the example below, and then check to see if the column name is
changed in the ``Covid\_19'' dataset. This example will be preformed
using a column \emph{not} of interest to our question(s)/hypothesis(s).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Covid\_19}\OtherTok{\textless{}{-}} \FunctionTok{rename}\NormalTok{(Covid\_19, }\AttributeTok{Influenza =} \StringTok{"Influenza.Deaths"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

For practice, try renaming the ``Pneumonia.Deaths'' to ``Pneumonia''
using this structure outline.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Type Here}
\end{Highlighting}
\end{Shaded}

\#\#Check Packaging:

Next, the packaging of the dataframe should be assessed. This validates
that the dataframe is complete and is properly loaded. This can be
complete using simple R commands. We can look at the number of columns
and rows that the dataframe has.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ncol}\NormalTok{(Covid\_19)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{nrow}\NormalTok{(Covid\_19)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 82620
\end{verbatim}

As the output of this code chuck matches the expected number of
variables and observations (as displayed in the ``Global Environment''),
it can be assumed that the dataframe was uploaded correctly (although it
can be checked by creating a table; a function performed later in this
section).

\#\#Run str()

Another general exploration tool that should be completed before
analysis is running the structure of the dataframe. The output of this
command replicates some knowledge we already have, however, it is
another clean visual of the composition of the data and is an additional
method to catch potential problems in the dataframe before analysis.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(Covid\_19)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## spec_tbl_df [82,620 x 16] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ Data.As.Of                              : chr [1:82620] "02/09/2022" "02/09/2022" "02/09/2022" "02/09/2022" ...
##  $ Start.Date                              : chr [1:82620] "01/01/2020" "01/01/2020" "01/01/2020" "01/01/2020" ...
##  $ End.Date                                : chr [1:82620] "02/05/2022" "02/05/2022" "02/05/2022" "02/05/2022" ...
##  $ Group                                   : chr [1:82620] "By Total" "By Total" "By Total" "By Total" ...
##  $ Year                                    : num [1:82620] NA NA NA NA NA NA NA NA NA NA ...
##  $ Month                                   : num [1:82620] NA NA NA NA NA NA NA NA NA NA ...
##  $ State                                   : chr [1:82620] "United States" "United States" "United States" "United States" ...
##  $ Sex                                     : chr [1:82620] "All Sexes" "All Sexes" "All Sexes" "All Sexes" ...
##  $ Age.Group                               : chr [1:82620] "All Ages" "Under 1 year" "0-17 years" "1-4 years" ...
##  $ COVID.19.Deaths                         : num [1:82620] 898699 203 795 93 244 ...
##  $ Total.Deaths                            : num [1:82620] 7070005 39473 70082 7377 11756 ...
##  $ Pneumonia.Deaths                        : num [1:82620] 798605 456 1345 271 390 ...
##  $ Pneumonia.and.COVID.19.Deaths           : num [1:82620] 466948 26 223 25 84 ...
##  $ Influenza                               : num [1:82620] 10229 24 193 65 81 ...
##  $ Pneumonia..Influenza..or.COVID.19.Deaths: num [1:82620] 1239112 657 2110 404 631 ...
##  $ Footnote                                : chr [1:82620] NA NA NA NA ...
##  - attr(*, "spec")=
##   .. cols(
##   ..   `Data As Of` = col_character(),
##   ..   `Start Date` = col_character(),
##   ..   `End Date` = col_character(),
##   ..   Group = col_character(),
##   ..   Year = col_double(),
##   ..   Month = col_double(),
##   ..   State = col_character(),
##   ..   Sex = col_character(),
##   ..   `Age Group` = col_character(),
##   ..   `COVID-19 Deaths` = col_number(),
##   ..   `Total Deaths` = col_number(),
##   ..   `Pneumonia Deaths` = col_number(),
##   ..   `Pneumonia and COVID-19 Deaths` = col_number(),
##   ..   `Influenza Deaths` = col_number(),
##   ..   `Pneumonia, Influenza, or COVID-19 Deaths` = col_number(),
##   ..   Footnote = col_character()
##   .. )
##  - attr(*, "problems")=<externalptr>
\end{verbatim}

Immediately, one may notice the NA values listed for the year and month
columns. These should be further evaluated. By rescrolling through the
``Covid\_19'' dataframe, we can note that these NA values come from data
that has been grouped. Grouped data, such as the Year and Month, make
some values/anlaysis obsolete. ``By total'' data may be useful for
future data as it is clean and easy to work with. Less filtering, as we
will discuss later, may be required.

Beyond the NA values in the dataframe, there appears to be no other
apparent issues. For future analysis using R beyond this project,
however, NA values should always be evaluated as it could indicate
missing variables or erroneous data that can not be used.

\#\#Check Top and Bottom of Data:

Assessing the beginning and end of the dataframe is a useful tool to
assure the data was loaded in property, the data is properly formatted,
and that all expected data is present. Should dates be present in the
dataframe, this technique is useful to check the ordering of them.

The ``Covid\_19'' dataframe has dates and the ordering should be
evaluated. This can be completed via the head and tail R commands. The
structure of this commands is as follows: head/tail(dataframe{[},
c(column:column, \#rows){]}).

The brackets in this structure are a useful way to filter data via the
use of a preloaded packaged (dplyr). An immediate comma is placed after
the bracket to specify the filtering of data from a column. Typical use
of brackets are structured as {[}row, column{]}. The c command allows
for a string of commands. Finally, we can specify a range of columns of
interest and the number of rows of data desired.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(Covid\_19[, }\FunctionTok{c}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{, }\DecValTok{10}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 4
##   Data.As.Of Start.Date End.Date   COVID.19.Deaths
##   <chr>      <chr>      <chr>                <dbl>
## 1 02/09/2022 01/01/2020 02/05/2022          898699
## 2 02/09/2022 01/01/2020 02/05/2022             203
## 3 02/09/2022 01/01/2020 02/05/2022             795
## 4 02/09/2022 01/01/2020 02/05/2022              93
## 5 02/09/2022 01/01/2020 02/05/2022             244
## 6 02/09/2022 01/01/2020 02/05/2022            2347
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tail}\NormalTok{(Covid\_19[, }\FunctionTok{c}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{, }\DecValTok{10}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 4
##   Data.As.Of Start.Date End.Date   COVID.19.Deaths
##   <chr>      <chr>      <chr>                <dbl>
## 1 02/09/2022 02/01/2022 02/05/2022               0
## 2 02/09/2022 02/01/2022 02/05/2022               0
## 3 02/09/2022 02/01/2022 02/05/2022               0
## 4 02/09/2022 02/01/2022 02/05/2022               0
## 5 02/09/2022 02/01/2022 02/05/2022               0
## 6 02/09/2022 02/01/2022 02/05/2022               0
\end{verbatim}

By looking at the start dates, we can see that the dataframe is logical.
At the head (first ten rows), the data collection start date began in
January of 2020. At the tail of the dataframe (last ten rows), the start
date began in February of 2022.

Additionally, the tail command can be useful for identifying extraneous
values or information placed at the end of the dataframe.

\#\#Check Observations (N's):

For data exploration, it is helpful to identify landmarks within a
dataframe that can be used to check against the data being evaluated.
This can be done a number of ways, but simply, a table can be made. For
example, the ``Covid\_19'' dataframe has distinguished variables that
look at Sex and State observations. These variables can be crosschecked
by the analysis to assure that the expected amount of observations are
present.

The table function can be utilized in R. The structure of the command is
as follows: table(dataframe\$variable). The dollar sign can be used to
narrow analysis by column within a dataframe.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(Covid\_19}\SpecialCharTok{$}\NormalTok{Sex)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## All Sexes    Female      Male 
##     27540     27540     27540
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(Covid\_19}\SpecialCharTok{$}\NormalTok{State)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##              Alabama               Alaska              Arizona 
##                 1530                 1530                 1530 
##             Arkansas           California             Colorado 
##                 1530                 1530                 1530 
##          Connecticut             Delaware District of Columbia 
##                 1530                 1530                 1530 
##              Florida              Georgia               Hawaii 
##                 1530                 1530                 1530 
##                Idaho             Illinois              Indiana 
##                 1530                 1530                 1530 
##                 Iowa               Kansas             Kentucky 
##                 1530                 1530                 1530 
##            Louisiana                Maine             Maryland 
##                 1530                 1530                 1530 
##        Massachusetts             Michigan            Minnesota 
##                 1530                 1530                 1530 
##          Mississippi             Missouri              Montana 
##                 1530                 1530                 1530 
##             Nebraska               Nevada        New Hampshire 
##                 1530                 1530                 1530 
##           New Jersey           New Mexico             New York 
##                 1530                 1530                 1530 
##        New York City       North Carolina         North Dakota 
##                 1530                 1530                 1530 
##                 Ohio             Oklahoma               Oregon 
##                 1530                 1530                 1530 
##         Pennsylvania          Puerto Rico         Rhode Island 
##                 1530                 1530                 1530 
##       South Carolina         South Dakota            Tennessee 
##                 1530                 1530                 1530 
##                Texas        United States                 Utah 
##                 1530                 1530                 1530 
##              Vermont             Virginia           Washington 
##                 1530                 1530                 1530 
##        West Virginia            Wisconsin              Wyoming 
##                 1530                 1530                 1530
\end{verbatim}

The net number of observations from each variable category (whether sex
or state) should equals the amount of observations present in the
dataframe, as there should be one entry for every observation. In this
case, the numbers within each column matches the total number of
observations, which is reassuring (27540 x 3 ``sex categories = 82,620
observations, and 1,530 x 54''states'' = 82,620 observations).

By looking at the states, however, we note that Puerto Rico, District of
Columbia, New York City, and United States area all included on the
dataset. While these locations have been included because they are US
territory, locations of interest, or label data representative of the
entire country instead of a state, this is important to take note of. It
is up to the epidemiologist, in later sections, to determine whether
these locations should be included in analysis depending on the question
at hand, but this is a prime example of how exploring the dataset is an
essential step when working with R Studio.

\#\#Other Checks to Consider:

After an initial check over the dataframe has been complete, there are
other factors to consider. For this purpose of this R tutorial, they
will not be completed in full, but rather highlighted as things to be
consider when conducting data analysis beyond this project. The first
additional rule of thumb to consider is the validation of ones own data
via a comparison with an external source. The CDC is very reliable,
thus, the observations in this dataframe do not necessarily have be
check. However, should further investigation be complete, eternal
sources to consider include datasets from Johns Hopkins or Our World in
Data. If one is using their own research data, they would certainly
attempt an external validation of data. They would want to compare
observations and numeric variables against another reliable source to
conclude the absence of erroneous data.

An additional consideration is to try to answer ones question/hypothesis
in the easiest way possible. Say your question simply asks which state
had the most COVID-19 death in 2020. The data can simply be filtered out
using a table. Certain questions like these do not need further
exploration. The solution to these questions, however, should be
challenged if possible. Factors such as some states not reporting data
could be an issue (this is one such example, but this problem is not
present in the ``Covid\_19'' dataframe).

The purpose of this concluding paragraph on exploration of a dataset is
to raise the point that not all questions require a deep dive into data
analysis, rather, just a basic R exploration. Questions that compare
variables, look at causality, and evaluate relationships, however, do
require a lengthier analysis.

\#VISUALIZATION OF DATASET AND VARIABLES OF INTEREST:

Before we begin visualization of our dataset, we should familiarize
ourselves with some key ggplot functions. Below is a general template
with explanations of functions that one can use when creating a plot.

Create a graph name and graph using the ggplot package a. Think of a
title for the plot. Redefine dataframe via \textless-ggplot() b. The
structure of a basic ggplot is as follows: (data.frame, aes(x=column, y=
column)) -Unless specified, R will choose the best fit plot with the
given data (it might not be the desired plot you want) -aes= axis.
Define the x and y axis of your plot by the independent and dependent
variable. c.~Specify the plot you wish ggplot to create. Lets create a
point plot with a line. The structure of this command is as follows:
geom\_() -Geom\_point creates a line graph. You can leave it here or add
a binary variable -Binary variables can be distinguished by the function
colour =factor(BV). -All data points can be added via the jitter
command. Add position= ``jitter''. This is useful for visualize
independent data points -The size and transparency of these data points
can be defined using the commands alpha= and size= d.~If desired,
specify a line of best fit with standard deviation. Use command
geom\_smoooth. The structure of this command is as follows:
geom\_smooth(formula = y \textasciitilde{} x,method=`lm',aes(group =
factor(BV), colour = factor(BV))) -The formula is specified as
y\textasciitilde x as a linear line is desired -Method='lm'' to specify
a linear model -Group and colour should equal factor of the binary
variable e. Clean the graph up by changing: -Change legend position by
using theme function of ggplot: theme(legend.position = ``right, left,
top, bottom'') -Change title of plot via function: ggtitle(``Title'')
-Change name of x/y axis and legend title via function: labs(x= ``X
Title'', y= ``Y Title'', color= ``Legend Title'') OR you can
individually state the x/y axis labels via xlab(``Title'') and
ylab(``Title'') -Change aesthetics of x axis categories via function:
theme(axis.text.x = element\_text(angle = 1-180, vjust = numeric,
hjust=numeric)) f.~A string of commands can be accomplished using ``+''
after each line of code. g. Apply theme\_cowplot() which provides a
classical plot appearance with two axis lines and no background grid h.
Plot using function plot(name of designated plot)

Above is general outline that can be modified. Elements can be added or
removed based on desired aesthetic appearance. The ggplot packaged also
plots more than line graphs. A master list can be found at this link:

\url{http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Plotting Data of COVID-19 Deaths by year and month.
\end{enumerate}

This is a great way to start looking at the data set. Here we can get a
visualization of how the data is spread out over years and then narrow
in per month.

This first plot shows COVID-19 Deaths per year.

The plotting of this question and data requires the use of the filter
function. Specific observations can be filtered from the ``Covid\_19''
data frame. This can be completed using the highly useful ``filter''
command. The structure of the filter command is as follows: new data
frame name\textless-filter(old data frame name,
column==/!=/\textgreater=/\textless= ``Info from column'')

Filtering can be accomplished by specifying what one would like to
take/remove from the original data frame. One can use the following to:
==: Specify data that is equivalent to (think keep data) !=: Specify
data that is not equal to (think remove data) \textless=: Specify data
less than desired numeric data (use greater than sign for reverse
process) \&: Multiple filter commands; make a string of commands

Listed above are simply introductory commands that are used in
conjunction with the filter command. Keep in mind, however, there are
additional commands like is.na(), between(), and near() that can be used
for advanced filtration. For the purpose of this project, we will mainly
focus on the introductory commands.

Below we use filter to look at the data grouped by month. group\_by is
used to group the data by Year and Month. The following ggplot helps us
visualize Covid 19 deaths per year.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CovidFilter }\OtherTok{\textless{}{-}} \FunctionTok{filter}\NormalTok{(Covid\_19, Group }\SpecialCharTok{==} \StringTok{"By Month"}\NormalTok{)}
\NormalTok{CovidYear }\OtherTok{\textless{}{-}} \FunctionTok{group\_by}\NormalTok{(CovidFilter, Year, Month)}

\FunctionTok{ggplot}\NormalTok{(CovidYear) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{aes}\NormalTok{(}\AttributeTok{x=} \FunctionTok{factor}\NormalTok{(Year), }\AttributeTok{y=}\NormalTok{ COVID.}\FloatTok{19.}\NormalTok{Deaths) }\SpecialCharTok{+} 
    \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Covid 19 Deaths per Year"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Year"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Covid 19 Deaths"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{theme\_cowplot}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 18330 rows containing missing values (geom_point).

## Warning: Removed 18330 rows containing missing values (geom_point).
\end{verbatim}

\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-9-1.pdf}

Next, we can visualize if there is a difference in COVID-19 Deaths per
month.

Additional modifications to the plotting outline are needed. One can use
the dplyr function group\_by to group desired data from different
columns/variables in a dataframe. In addition, we want to run the Month
X-variable as a factor, instead of a numerical variable. This
distinction is made within the aes() function, and is necessary to
obtain the appropriate x-axis values. If you are curious about this
functions effect, change ``aes(x= factor(Month), y= COVID.19.Deaths)''
to ``aes(x= Month, y=COVID.19.Deaths)'' for graph p1 and note the
difference.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CovidFilterMonth1 }\OtherTok{\textless{}{-}} \FunctionTok{filter}\NormalTok{(Covid\_19, Group }\SpecialCharTok{==} \StringTok{"By Month"}\NormalTok{, Year }\SpecialCharTok{==} \StringTok{"2020"}\NormalTok{) }\CommentTok{\#filter is used here to filter out all groups that are not organized by month. We also filtered by the Year so we will only see data for 2020.}
\NormalTok{CovidMonth1 }\OtherTok{\textless{}{-}} \FunctionTok{group\_by}\NormalTok{(CovidFilterMonth1, Year, Month) }\CommentTok{\#group\_by is used to group the data into Year and Month}

\CommentTok{\# p\# is used below to lable each graph to make it easier to visualize them together later.}
\NormalTok{p1 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(CovidMonth1) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{aes}\NormalTok{(}\AttributeTok{x=} \FunctionTok{factor}\NormalTok{(Month), }\AttributeTok{y=}\NormalTok{ COVID.}\FloatTok{19.}\NormalTok{Deaths) }\SpecialCharTok{+} 
    \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Deaths per Month in 2020"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Month"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Covid 19 Deaths"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{theme\_cowplot}\NormalTok{()}

\NormalTok{CovidFilterMonth2 }\OtherTok{\textless{}{-}} \FunctionTok{filter}\NormalTok{(Covid\_19, Group }\SpecialCharTok{==} \StringTok{"By Month"}\NormalTok{, Year }\SpecialCharTok{==} \StringTok{"2021"}\NormalTok{)}
\NormalTok{CovidMonth2 }\OtherTok{\textless{}{-}} \FunctionTok{group\_by}\NormalTok{(CovidFilterMonth2, Year, Month)}

\NormalTok{p2 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(CovidMonth2) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{aes}\NormalTok{(}\AttributeTok{x=} \FunctionTok{factor}\NormalTok{(Month), }\AttributeTok{y=}\NormalTok{ COVID.}\FloatTok{19.}\NormalTok{Deaths) }\SpecialCharTok{+} 
    \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Deaths per Month in 2021"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Month"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Covid 19 Deaths"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{theme\_cowplot}\NormalTok{()}

\NormalTok{CovidFilterMonth3 }\OtherTok{\textless{}{-}} \FunctionTok{filter}\NormalTok{(Covid\_19, Group }\SpecialCharTok{==} \StringTok{"By Month"}\NormalTok{, Year }\SpecialCharTok{==} \StringTok{"2022"}\NormalTok{)}
\NormalTok{CovidMonth3 }\OtherTok{\textless{}{-}} \FunctionTok{group\_by}\NormalTok{(CovidFilterMonth2, Year, Month)}

\NormalTok{p3 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(CovidMonth3) }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{aes}\NormalTok{(}\AttributeTok{x=} \FunctionTok{factor}\NormalTok{(Month), }\AttributeTok{y=}\NormalTok{ COVID.}\FloatTok{19.}\NormalTok{Deaths) }\SpecialCharTok{+} 
    \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Deaths per Month in 2022"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Month"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Covid 19 Deaths"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{theme\_cowplot}\NormalTok{()}

\FunctionTok{plot\_grid}\NormalTok{(p1,p2,p3,}\AttributeTok{ncol=}\DecValTok{2}\NormalTok{) }\CommentTok{\#plot\_grid allows us to plot all of the graphs next to one another for easier comparison}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 7701 rows containing missing values (geom_point).

## Warning: Removed 7701 rows containing missing values (geom_point).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 9318 rows containing missing values (geom_point).

## Warning: Removed 9318 rows containing missing values (geom_point).

## Warning: Removed 9318 rows containing missing values (geom_point).

## Warning: Removed 9318 rows containing missing values (geom_point).
\end{verbatim}

\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Plots tp visualize if older individuals have higher death rates than
  younger individuals.
\end{enumerate}

You may have noticed comments being made in code chucks that do not
interfere with running the code. These are denoted with a \# and are
shown in green. This is valuable tactic used to walk individuals
(familiar or unfamiliar with the dataframe) through the code.

Furthermore, note in this next code chuck, the operator \%\textgreater\%
will be utilized from the Dplyr package to allow for pipeline commands.
This is a close equivalent to using ``+'' in ggplot.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr) }\CommentTok{\#Calls the dplyr package to run subsequential code}
\NormalTok{Covid\_19 }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\#Calls the Covid\_19 dataset to be acted on by the following functions}
  \FunctionTok{filter}\NormalTok{(State }\SpecialCharTok{==} \StringTok{"United States"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\#Selects only the data total deaths in the United States independent of State}
  \FunctionTok{filter}\NormalTok{(Sex }\SpecialCharTok{==} \StringTok{"All Sexes"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\#Selects deaths from all sexes, excluding repetitive Male/Female subdivisions}
  \FunctionTok{filter}\NormalTok{(Group }\SpecialCharTok{==} \StringTok{"By Total"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\#Selects total deaths to date, excluding repetitive by month/year subdivisions}
  \FunctionTok{summarize}\NormalTok{(State, Sex, Age.Group, COVID.}\FloatTok{19.}\NormalTok{Deaths) }\OtherTok{{-}\textgreater{}}\NormalTok{ Covid\_19.Deaths.by.Age }\CommentTok{\#Selects only the relavent columns to our analysis and saves them to a new dataset titled "Covid\_19.Deaths.by.Age"}

\FunctionTok{table}\NormalTok{(Covid\_19.Deaths.by.Age}\SpecialCharTok{$}\NormalTok{Age.Group)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##        0-17 years         1-4 years       15-24 years       18-29 years 
##                 1                 1                 1                 1 
##       25-34 years       30-39 years       35-44 years       40-49 years 
##                 1                 1                 1                 1 
##       45-54 years        5-14 years       50-64 years       55-64 years 
##                 1                 1                 1                 1 
##       65-74 years       75-84 years 85 years and over          All Ages 
##                 1                 1                 1                 1 
##      Under 1 year 
##                 1
\end{verbatim}

After running this new code chuck, the new data frame
``Covid\_19.Deaths.by.Age'' was created from the previous ``Covid\_19''
data frame, and is present in the ``Global Environment''/Environment
tab. In this data frame, one will notice that only 17 of the original
82620 observations are included, with only the 4 variables/columns of
data specified by the summarize function above. Furthermore, notice how
``State==''United States''\,'' command kept data from that one
particular ``State''. Additionally, note how the same is true for
observations categorized as ``All Sexes'' and ``By Total'' in the Sex
and Group column.

This general theme of grouped data, as mentioned earlier in the project,
is something to beware of. Be cautious when analyzing data and filtering
data for statistical analysis.

However, as our table function shows above, our filtering process is not
complete. Notice that some of the listed age ranges have repetitive
data, and if one aims to make a coherent graph, one should not have
overlap between age groups. In addition, note that the adolescent
observations collected data at a different age intervals that are not
consistent with the way the adult age intervals collected. Thus, one is
forced to look at age range 0-1 years for newborns, 1-4 years for young
children, followed by a consistent 9 year interval range through adult
hood.

This is OKAY, but should be noted with analysis. There was simply
inconsistency with data collection that is beyond our control.

The code below shows how we can eliminate Ages that overlap with the
``!='' operator in the filter command.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Covid\_19.Deaths.by.Age }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Age.Group }\SpecialCharTok{!=} \StringTok{"0{-}17 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group }\SpecialCharTok{!=} \StringTok{"All Ages"} \SpecialCharTok{\&}\NormalTok{ Age.Group }\SpecialCharTok{!=} \StringTok{"50{-}64 years"}\NormalTok{) }\OtherTok{{-}\textgreater{}}\NormalTok{Covid\_19.Deaths.by.Age }\CommentTok{\#removing 0{-}17 years, All Ages and 55 {-} 64 years observations, and saves the resulting data frame over the preexisting one (note the number of observations decreasing to 14)}

\FunctionTok{table}\NormalTok{(Covid\_19.Deaths.by.Age}\SpecialCharTok{$}\NormalTok{Age.Group)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##         1-4 years       15-24 years       18-29 years       25-34 years 
##                 1                 1                 1                 1 
##       30-39 years       35-44 years       40-49 years       45-54 years 
##                 1                 1                 1                 1 
##        5-14 years       55-64 years       65-74 years       75-84 years 
##                 1                 1                 1                 1 
## 85 years and over      Under 1 year 
##                 1                 1
\end{verbatim}

While we are close to being able to plot this data, the order in which
the years are listed is skewed. This order would be reflected on our
graph if we were to choose to graph this subset of our data without
further modification. By using the ``recode\_factor'' function below, we
can rename the groups so that automatic numerical ordering will place
them in a coherent order.

The format for the recode factor matches the following:
``dataset\(specific.column.in.dataset<-recode_factor(dataset\)specific.column.in.dataset,
\texttt{Previous\ Name}=''New Name'', etc.)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Covid\_19.Deaths.by.Age}\SpecialCharTok{$}\NormalTok{Age.Group}\OtherTok{\textless{}{-}}\FunctionTok{recode\_factor}\NormalTok{(Covid\_19.Deaths.by.Age}\SpecialCharTok{$}\NormalTok{Age.Group, }\StringTok{\textasciigrave{}}\AttributeTok{Under 1 year}\StringTok{\textasciigrave{}} \OtherTok{=} \StringTok{"0{-}1 years"}\NormalTok{, }\StringTok{\textasciigrave{}}\AttributeTok{1{-}4 years}\StringTok{\textasciigrave{}} \OtherTok{=} \StringTok{"01{-}4 years"}\NormalTok{, }\StringTok{\textasciigrave{}}\AttributeTok{5{-}14 years}\StringTok{\textasciigrave{}} \OtherTok{=} \StringTok{"05{-}14 years"}\NormalTok{)}

\FunctionTok{table}\NormalTok{(Covid\_19.Deaths.by.Age}\SpecialCharTok{$}\NormalTok{Age.Group)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##         0-1 years        01-4 years       05-14 years       15-24 years 
##                 1                 1                 1                 1 
##       18-29 years       25-34 years       30-39 years       35-44 years 
##                 1                 1                 1                 1 
##       40-49 years       45-54 years       55-64 years       65-74 years 
##                 1                 1                 1                 1 
##       75-84 years 85 years and over 
##                 1                 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#validating change}
\end{Highlighting}
\end{Shaded}

Notice how now the years are ordered in a logical manner, and we are
ready to graph the data.

The following steps take place in order to perform this. This code
extends upon the steps used in part 1 of this data visualization section
(again, note the comments explaining what each line of code is doing):

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2) }\CommentTok{\#Calls the ggplot package for use in subsequent code}
\NormalTok{US.Deaths.by.Age}\OtherTok{\textless{}{-}}\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{Covid\_19.Deaths.by.Age) }\SpecialCharTok{+} \CommentTok{\#Saves the produced graph as "US.Deaths.by.Age" to Environment tab}
  \FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Age.Group, }\AttributeTok{y=}\NormalTok{COVID.}\FloatTok{19.}\NormalTok{Deaths) }\SpecialCharTok{+} \CommentTok{\#defines variables for the X and Y axis}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat=}\StringTok{"identity"}\NormalTok{) }\SpecialCharTok{+} \CommentTok{\#Defines the graph as a bar graph with Y values that are identical to the observational values}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"COVID{-}19 Deaths by Age in the United States"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x=} \StringTok{"Age Group"}\NormalTok{, }\AttributeTok{y=} \StringTok{"COVID{-}19 Deaths"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{50}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.7}\NormalTok{, }\AttributeTok{hjust=}\FloatTok{0.5}\NormalTok{)) }\CommentTok{\#adjusts x{-}axis positioning}
  

\NormalTok{US.Deaths.by.Age }\CommentTok{\#Calls previously created graph to be displayed}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-14-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Code for Ranking net Deaths by State
\end{enumerate}

We can also sort the data to see which state has the most Covid\_19
deaths over the course of the pandemic. By now, you should have a
toolbox of coding techniques large enough to follow along with this
analysis. Functions that have not been previously shown will have a
comment explaining them next to them with general descriptions.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\NormalTok{Covid\_19}\SpecialCharTok{$}\NormalTok{State}\OtherTok{\textless{}{-}}\FunctionTok{as\_factor}\NormalTok{(Covid\_19}\SpecialCharTok{$}\NormalTok{State)}
\FunctionTok{nlevels}\NormalTok{(Covid\_19}\SpecialCharTok{$}\NormalTok{State) }\CommentTok{\#Shows us how many observations are within each level (or State) of the factor.}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 54
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(Covid\_19}\SpecialCharTok{$}\NormalTok{State) }\CommentTok{\#Shows us the number of different "State" values there are by showing a number of how many unique levels the vector has}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##        United States              Alabama               Alaska 
##                 1530                 1530                 1530 
##              Arizona             Arkansas           California 
##                 1530                 1530                 1530 
##             Colorado          Connecticut             Delaware 
##                 1530                 1530                 1530 
## District of Columbia              Florida              Georgia 
##                 1530                 1530                 1530 
##               Hawaii                Idaho             Illinois 
##                 1530                 1530                 1530 
##              Indiana                 Iowa               Kansas 
##                 1530                 1530                 1530 
##             Kentucky            Louisiana                Maine 
##                 1530                 1530                 1530 
##             Maryland        Massachusetts             Michigan 
##                 1530                 1530                 1530 
##            Minnesota          Mississippi             Missouri 
##                 1530                 1530                 1530 
##              Montana             Nebraska               Nevada 
##                 1530                 1530                 1530 
##        New Hampshire           New Jersey           New Mexico 
##                 1530                 1530                 1530 
##             New York        New York City       North Carolina 
##                 1530                 1530                 1530 
##         North Dakota                 Ohio             Oklahoma 
##                 1530                 1530                 1530 
##               Oregon         Pennsylvania         Rhode Island 
##                 1530                 1530                 1530 
##       South Carolina         South Dakota            Tennessee 
##                 1530                 1530                 1530 
##                Texas                 Utah              Vermont 
##                 1530                 1530                 1530 
##             Virginia           Washington        West Virginia 
##                 1530                 1530                 1530 
##            Wisconsin              Wyoming          Puerto Rico 
##                 1530                 1530                 1530
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Covid\_19}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{ (State }\SpecialCharTok{!=} \StringTok{"United States"} \SpecialCharTok{\&}\NormalTok{ State }\SpecialCharTok{!=} \StringTok{"District of Columbia"} \SpecialCharTok{\&}\NormalTok{ State }\SpecialCharTok{!=} \StringTok{"New York City"} \SpecialCharTok{\&}\NormalTok{ State }\SpecialCharTok{!=} \StringTok{"Puerto Rico"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Group }\SpecialCharTok{==} \StringTok{"By Total"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Sex }\SpecialCharTok{==} \StringTok{"All Sexes"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(Age.Group }\SpecialCharTok{==} \StringTok{"All Ages"}\NormalTok{) }\OtherTok{{-}\textgreater{}}\NormalTok{Covid\_19.State.Deaths}
\end{Highlighting}
\end{Shaded}

To ensure the filtering process worked and observe the results:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(Covid\_19.State.Deaths}\SpecialCharTok{$}\NormalTok{State)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##        United States              Alabama               Alaska 
##                    0                    1                    1 
##              Arizona             Arkansas           California 
##                    1                    1                    1 
##             Colorado          Connecticut             Delaware 
##                    1                    1                    1 
## District of Columbia              Florida              Georgia 
##                    0                    1                    1 
##               Hawaii                Idaho             Illinois 
##                    1                    1                    1 
##              Indiana                 Iowa               Kansas 
##                    1                    1                    1 
##             Kentucky            Louisiana                Maine 
##                    1                    1                    1 
##             Maryland        Massachusetts             Michigan 
##                    1                    1                    1 
##            Minnesota          Mississippi             Missouri 
##                    1                    1                    1 
##              Montana             Nebraska               Nevada 
##                    1                    1                    1 
##        New Hampshire           New Jersey           New Mexico 
##                    1                    1                    1 
##             New York        New York City       North Carolina 
##                    1                    0                    1 
##         North Dakota                 Ohio             Oklahoma 
##                    1                    1                    1 
##               Oregon         Pennsylvania         Rhode Island 
##                    1                    1                    1 
##       South Carolina         South Dakota            Tennessee 
##                    1                    1                    1 
##                Texas                 Utah              Vermont 
##                    1                    1                    1 
##             Virginia           Washington        West Virginia 
##                    1                    1                    1 
##            Wisconsin              Wyoming          Puerto Rico 
##                    1                    1                    0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{nlevels}\NormalTok{(Covid\_19.State.Deaths}\SpecialCharTok{$}\NormalTok{State)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 54
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{arrange}\NormalTok{(Covid\_19.State.Deaths,}\FunctionTok{desc}\NormalTok{(COVID.}\FloatTok{19.}\NormalTok{Deaths)) }\CommentTok{\#arranges the data from the state with the highest number of deaths to the state with the lowest number of death}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 50 x 16
##    Data.As.Of Start.Date End.Date   Group     Year Month State   Sex   Age.Group
##    <chr>      <chr>      <chr>      <chr>    <dbl> <dbl> <fct>   <chr> <chr>    
##  1 02/09/2022 01/01/2020 02/05/2022 By Total    NA    NA Califo~ All ~ All Ages 
##  2 02/09/2022 01/01/2020 02/05/2022 By Total    NA    NA Texas   All ~ All Ages 
##  3 02/09/2022 01/01/2020 02/05/2022 By Total    NA    NA Florida All ~ All Ages 
##  4 02/09/2022 01/01/2020 02/05/2022 By Total    NA    NA Pennsy~ All ~ All Ages 
##  5 02/09/2022 01/01/2020 02/05/2022 By Total    NA    NA Ohio    All ~ All Ages 
##  6 02/09/2022 01/01/2020 02/05/2022 By Total    NA    NA New Yo~ All ~ All Ages 
##  7 02/09/2022 01/01/2020 02/05/2022 By Total    NA    NA Illino~ All ~ All Ages 
##  8 02/09/2022 01/01/2020 02/05/2022 By Total    NA    NA New Je~ All ~ All Ages 
##  9 02/09/2022 01/01/2020 02/05/2022 By Total    NA    NA Michig~ All ~ All Ages 
## 10 02/09/2022 01/01/2020 02/05/2022 By Total    NA    NA Georgia All ~ All Ages 
## # ... with 40 more rows, and 7 more variables: COVID.19.Deaths <dbl>,
## #   Total.Deaths <dbl>, Pneumonia.Deaths <dbl>,
## #   Pneumonia.and.COVID.19.Deaths <dbl>, Influenza <dbl>,
## #   Pneumonia..Influenza..or.COVID.19.Deaths <dbl>, Footnote <chr>
\end{verbatim}

Notice the first output frame shows that one observation (the data point
representing the total number of deaths in each state since the start of
the pandemic) remains in each state. Although there are 54 states total
in the list, the ones removed (United States, District of Columbia, New
York City, and Puerto Rico) all have no observations in their category,
effectively taking them out of the set. And finally, the second box
shows us the order of States with the most to least Covid-19 deaths with
California being first (85,545 deaths).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  West Coast vs East Coast COVID-19 Death Exploration
\end{enumerate}

Looking at differences in COVID-19 deaths between the East and West
coast creates a problem in our original dataset. We have no segregation
between these two variables. Thus, we must do so ourselves, and this can
be completed via the creation of a new column in our original
``Covid\_19'' data frame.

The creation of a new data frame with an additional column that
segretates the East and West coast states can be accomplished using the
mutate command. A new column can be created that creates binary values
of ``TRUE'' or ``FALSE'' where, for example, ``TRUE'' is equivalent to
states on the West coast and ``FALSE'' is equivalent to states on the
East coast.

One can use the Dpylr package to mutate their data frame. This package
is already preloaded into our RMD.

The structure of the mutate command is as follows: data
frame\%\textgreater\% mutate(Added column=Column manipulated \%in\%
c(specification of desired data)). This ``filtered'' should be replaced
into data frame (new or old)-\textgreater{} data frame.

Note \textless- and -\textgreater{} are the same function, but placement
at the begging or end of code specify usage.

Lets add a new column into the ``Covid\_19'' data frame and call it WC
for West Coast.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Covid\_19}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{WC=}\NormalTok{ State }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Alaska"}\NormalTok{,}\StringTok{"Arizona"}\NormalTok{,}\StringTok{"Arkansas"}\NormalTok{,}\StringTok{"California"}\NormalTok{,}\StringTok{"Colorado"}\NormalTok{,}\StringTok{"Hawaii"}\NormalTok{,}\StringTok{"Idaho"}\NormalTok{,}\StringTok{"Iowa"}\NormalTok{,}\StringTok{"Kansas"}\NormalTok{,}\StringTok{"Louisiana"}\NormalTok{,}\StringTok{"Minnesota"}\NormalTok{,}\StringTok{"Missouri"}\NormalTok{,}\StringTok{"Oregon"}\NormalTok{,}\StringTok{"South Dakota"}\NormalTok{,}\StringTok{"Texas"}\NormalTok{,}\StringTok{"Utah"}\NormalTok{,}\StringTok{"Washington"}\NormalTok{,}\StringTok{"Wyoming"}\NormalTok{))}\OtherTok{{-}\textgreater{}}\NormalTok{Covid\_19}
\end{Highlighting}
\end{Shaded}

**Check to make sure new column as been added by opening up
``Covid\_19'' from the environment.

Now, lets utilize this new column and plot West coast vs East coast
COVID-19 death by sex while applying the same coding techniques learned
from previous sections. We should make a boxplot. In this code chuck, we
will exclude data from the ``States'' labeled ``United States'', ``New
York City'', and ``Puerto Rico'' because these are not traditional
states. Washington DC data will remain included based on preference.

Finally, we will add one new line of code. We can change the x axis
labels by incorporating the function: scale\_x\_discrete(labels =
c(`Title', `Title')). We will want to specify East from West coast.
Without this code, the labels will show up as ``FALSE'' and ``TRUE''.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CovidDataCoasts}\OtherTok{\textless{}{-}}\FunctionTok{filter}\NormalTok{(Covid\_19, Group}\SpecialCharTok{==}\StringTok{"By Total"} \SpecialCharTok{\&}\NormalTok{ Sex}\SpecialCharTok{!=}\StringTok{"All Sexes"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{==}\StringTok{"All Ages"} \SpecialCharTok{\&}\NormalTok{ State}\SpecialCharTok{!=}\StringTok{"United States"} \SpecialCharTok{\&}\NormalTok{ State}\SpecialCharTok{!=}\StringTok{"Puerto Rico"}\NormalTok{, State}\SpecialCharTok{!=} \StringTok{"New York City"}\NormalTok{ )}
\NormalTok{Coast1}\OtherTok{\textless{}{-}}\FunctionTok{ggplot}\NormalTok{(CovidDataCoasts) }\SpecialCharTok{+}
  \FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{WC , }\AttributeTok{y=}\NormalTok{COVID.}\FloatTok{19.}\NormalTok{Deaths) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{width=}\NormalTok{.}\DecValTok{15}\NormalTok{, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{color=}\NormalTok{Sex)) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Total Covid{-}19 Death vs East/West Coast"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x=}\StringTok{"Coast"}\NormalTok{, }\AttributeTok{y=}\StringTok{"COVID{-}19 Deaths"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_discrete}\NormalTok{(}\AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}East\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}West\textquotesingle{}}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{theme\_cowplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{0}\NormalTok{, }\AttributeTok{vjust =} \DecValTok{1}\NormalTok{, }\AttributeTok{hjust=}\FloatTok{0.5}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(Coast1)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-18-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(Covid\_19}\SpecialCharTok{$}\NormalTok{State)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##        United States              Alabama               Alaska 
##                 1530                 1530                 1530 
##              Arizona             Arkansas           California 
##                 1530                 1530                 1530 
##             Colorado          Connecticut             Delaware 
##                 1530                 1530                 1530 
## District of Columbia              Florida              Georgia 
##                 1530                 1530                 1530 
##               Hawaii                Idaho             Illinois 
##                 1530                 1530                 1530 
##              Indiana                 Iowa               Kansas 
##                 1530                 1530                 1530 
##             Kentucky            Louisiana                Maine 
##                 1530                 1530                 1530 
##             Maryland        Massachusetts             Michigan 
##                 1530                 1530                 1530 
##            Minnesota          Mississippi             Missouri 
##                 1530                 1530                 1530 
##              Montana             Nebraska               Nevada 
##                 1530                 1530                 1530 
##        New Hampshire           New Jersey           New Mexico 
##                 1530                 1530                 1530 
##             New York        New York City       North Carolina 
##                 1530                 1530                 1530 
##         North Dakota                 Ohio             Oklahoma 
##                 1530                 1530                 1530 
##               Oregon         Pennsylvania         Rhode Island 
##                 1530                 1530                 1530 
##       South Carolina         South Dakota            Tennessee 
##                 1530                 1530                 1530 
##                Texas                 Utah              Vermont 
##                 1530                 1530                 1530 
##             Virginia           Washington        West Virginia 
##                 1530                 1530                 1530 
##            Wisconsin              Wyoming          Puerto Rico 
##                 1530                 1530                 1530
\end{verbatim}

Additionally, we can plot West coast vs East coast deaths by age range.
Again, we will filter the age groups we wish to represent.

One additional line of code can be included. We can specify the labels
of the legend and the color of the represented binary factor. This can
be accomplished via the
command:scale\_colour\_manual(labels=c(``Title'', ``Title''), values=
c(``color'', ``color''))

Colors can be represented numerous ways in R. However, they can be
conveniently picked by utilizing this provided resource from Columbia
University.

\url{http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf}

This cheat sheet was created by Dr.~Ying Wei.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CovidDataCoasts1}\OtherTok{\textless{}{-}}\FunctionTok{filter}\NormalTok{(Covid\_19, Group}\SpecialCharTok{==}\StringTok{"By Total"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"All Ages"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"Under 1 year"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"1{-}4 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"5{-}14 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"15{-}24 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"25{-}34 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"35{-}44 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"45{-}54 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"55{-}64 years"} \SpecialCharTok{\&}\NormalTok{ State}\SpecialCharTok{!=}\StringTok{"United States"} \SpecialCharTok{\&}\NormalTok{ State}\SpecialCharTok{!=}\StringTok{"Puerto Rico"}\NormalTok{, Sex}\SpecialCharTok{!=}\StringTok{"Male"} \SpecialCharTok{\&}\NormalTok{ Sex}\SpecialCharTok{!=}\StringTok{"Female"}\NormalTok{)}
\NormalTok{Coast2}\OtherTok{\textless{}{-}}\FunctionTok{ggplot}\NormalTok{(CovidDataCoasts1, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Age.Group, }\AttributeTok{y =}\NormalTok{ COVID.}\FloatTok{19.}\NormalTok{Deaths)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{colour =} \FunctionTok{factor}\NormalTok{(WC)), }
             \AttributeTok{position =} \StringTok{"jitter"}\NormalTok{, }
             \AttributeTok{alpha =} \FloatTok{0.8}\NormalTok{,}
             \AttributeTok{size=}\FloatTok{0.05}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x,}\AttributeTok{method=}\StringTok{\textquotesingle{}lm\textquotesingle{}}\NormalTok{,}\FunctionTok{aes}\NormalTok{(}\AttributeTok{group =} \FunctionTok{factor}\NormalTok{(WC), }
                              \AttributeTok{colour =} \FunctionTok{factor}\NormalTok{(WC))) }\SpecialCharTok{+} 
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"right"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{\textquotesingle{}Covid{-}19 Deaths by Age Group (Total) \textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x=} \StringTok{"Age Group"}\NormalTok{, }\AttributeTok{y=} \StringTok{"COVID{-}19 Deaths"}\NormalTok{, }\AttributeTok{color=}\StringTok{"Legend"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_colour\_manual}\NormalTok{(}\AttributeTok{labels=}\FunctionTok{c}\NormalTok{(}\StringTok{"East"}\NormalTok{, }\StringTok{"West"}\NormalTok{), }\AttributeTok{values=} \FunctionTok{c}\NormalTok{(}\StringTok{"darkblue"}\NormalTok{, }\StringTok{"red"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \DecValTok{1}\NormalTok{, }\AttributeTok{hjust=}\FloatTok{0.5}\NormalTok{))}
  \FunctionTok{theme\_cowplot}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## List of 93
##  $ line                      :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : num 1
##   ..$ lineend      : chr "butt"
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ rect                      :List of 5
##   ..$ fill         : logi NA
##   ..$ colour       : logi NA
##   ..$ size         : num 0.5
##   ..$ linetype     : num 1
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_rect" "element"
##  $ text                      :List of 11
##   ..$ family       : chr ""
##   ..$ face         : chr "plain"
##   ..$ colour       : chr "black"
##   ..$ size         : num 14
##   ..$ hjust        : num 0.5
##   ..$ vjust        : num 0.5
##   ..$ angle        : num 0
##   ..$ lineheight   : num 0.9
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ title                     : NULL
##  $ aspect.ratio              : NULL
##  $ axis.title                : NULL
##  $ axis.title.x              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3.5points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.x.top          :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 3.5points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.x.bottom       : NULL
##  $ axis.title.y              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : num 90
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 3.5points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.y.left         : NULL
##  $ axis.title.y.right        :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : num -90
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 3.5points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text                 :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : chr "black"
##   ..$ size         : num 12
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x.top           :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 3points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x.bottom        : NULL
##  $ axis.text.y               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 1
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 3points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.y.left          : NULL
##  $ axis.text.y.right         :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 3points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.ticks                :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : NULL
##   ..$ lineend      : NULL
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ axis.ticks.x              : NULL
##  $ axis.ticks.x.top          : NULL
##  $ axis.ticks.x.bottom       : NULL
##  $ axis.ticks.y              : NULL
##  $ axis.ticks.y.left         : NULL
##  $ axis.ticks.y.right        : NULL
##  $ axis.ticks.length         : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ axis.ticks.length.x       : NULL
##  $ axis.ticks.length.x.top   : NULL
##  $ axis.ticks.length.x.bottom: NULL
##  $ axis.ticks.length.y       : NULL
##  $ axis.ticks.length.y.left  : NULL
##  $ axis.ticks.length.y.right : NULL
##  $ axis.line                 :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : NULL
##   ..$ lineend      : chr "square"
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ axis.line.x               : NULL
##  $ axis.line.x.top           : NULL
##  $ axis.line.x.bottom        : NULL
##  $ axis.line.y               : NULL
##  $ axis.line.y.left          : NULL
##  $ axis.line.y.right         : NULL
##  $ legend.background         : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.margin             : 'margin' num [1:4] 0points 0points 0points 0points
##   ..- attr(*, "unit")= int 8
##  $ legend.spacing            : 'simpleUnit' num 14points
##   ..- attr(*, "unit")= int 8
##  $ legend.spacing.x          : NULL
##  $ legend.spacing.y          : NULL
##  $ legend.key                : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.key.size           : 'simpleUnit' num 15.4points
##   ..- attr(*, "unit")= int 8
##  $ legend.key.height         : NULL
##  $ legend.key.width          : NULL
##  $ legend.text               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ legend.text.align         : NULL
##  $ legend.title              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ legend.title.align        : NULL
##  $ legend.position           : chr "right"
##  $ legend.direction          : NULL
##  $ legend.justification      : chr [1:2] "left" "center"
##  $ legend.box                : NULL
##  $ legend.box.just           : NULL
##  $ legend.box.margin         : 'margin' num [1:4] 0points 0points 0points 0points
##   ..- attr(*, "unit")= int 8
##  $ legend.box.background     : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.box.spacing        : 'simpleUnit' num 14points
##   ..- attr(*, "unit")= int 8
##  $ panel.background          : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.border              : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.spacing             : 'simpleUnit' num 7points
##   ..- attr(*, "unit")= int 8
##  $ panel.spacing.x           : NULL
##  $ panel.spacing.y           : NULL
##  $ panel.grid                : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.grid.major          : NULL
##  $ panel.grid.minor          : NULL
##  $ panel.grid.major.x        : NULL
##  $ panel.grid.major.y        : NULL
##  $ panel.grid.minor.x        : NULL
##  $ panel.grid.minor.y        : NULL
##  $ panel.ontop               : logi FALSE
##  $ plot.background           : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ plot.title                :List of 11
##   ..$ family       : NULL
##   ..$ face         : chr "bold"
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 1.14
##   ..$ hjust        : num 0
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 7points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.title.position       : chr "panel"
##  $ plot.subtitle             :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : num 0
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 7points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.caption              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.786
##   ..$ hjust        : num 1
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 7points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.caption.position     : chr "panel"
##  $ plot.tag                  :List of 11
##   ..$ family       : NULL
##   ..$ face         : chr "bold"
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : num 0.7
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.tag.position         : num [1:2] 0 1
##  $ plot.margin               : 'margin' num [1:4] 7points 7points 7points 7points
##   ..- attr(*, "unit")= int 8
##  $ strip.background          :List of 5
##   ..$ fill         : chr "grey80"
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_rect" "element"
##  $ strip.background.x        : NULL
##  $ strip.background.y        : NULL
##  $ strip.placement           : chr "inside"
##  $ strip.text                :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3.5points 3.5points 3.5points 3.5points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ strip.text.x              : NULL
##  $ strip.text.y              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : num -90
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ strip.switch.pad.grid     : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ strip.switch.pad.wrap     : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ strip.text.y.left         :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : num 90
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  - attr(*, "class")= chr [1:2] "theme" "gg"
##  - attr(*, "complete")= logi TRUE
##  - attr(*, "validate")= logi TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(Coast2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 29 rows containing non-finite values (stat_smooth).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 29 rows containing missing values (geom_point).
\end{verbatim}

\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-19-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Plotting Data of COVID-19 Deaths from Pennsylvania (Total)
\end{enumerate}

To really narrow analysis, we can further look at the number of COVID-19
deaths per year and month in Pennsylvania. The state of Pennsylvania was
chosen for epidemiological relevance. Furthermore, refining the dataset
to a single state is beneficial for improved data visualization.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PennData}\OtherTok{\textless{}{-}}\FunctionTok{filter}\NormalTok{(Covid\_19, Sex}\SpecialCharTok{!=}\StringTok{"All Sexes"} \SpecialCharTok{\&}\NormalTok{ State}\SpecialCharTok{==}\StringTok{"Pennsylvania"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

After running this new code chuck, note the new data frame ``PennData''
created from the ``Covid\_19'' data frame.

This data frame can be further refined using the filter function to
explore COVID-19 deaths by Age, Group, and Year similar to as what was
previously completed in earlier sections. Note that the filtered
``PennData'' data frame is now being saved as ``CovidDataPennTotal'',
and that the number of observations in the data frame is decreasing as
we continue to focus in on certain data.

The problem of adolescent observations having different age intervals
that are not consistent with the way the adult age intervals collected
is one again a problem here, however, the age groups that are included
in the analysis are broken up differently. See if you can look at the
filter code below before running the analysis, compare it to the code in
part 2 of the ``Visualizing the Data'' section, and see how the filter
code for age ranges differs.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CovidDataPennTotal}\OtherTok{\textless{}{-}}\FunctionTok{filter}\NormalTok{(PennData, Group}\SpecialCharTok{==}\StringTok{"By Total"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"All Ages"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"Under 1 year"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"1{-}4 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"5{-}14 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"15{-}24 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"25{-}34 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"35{-}44 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"45{-}54 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{!=}\StringTok{"55{-}64 years"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PennTotal}\OtherTok{\textless{}{-}}\FunctionTok{ggplot}\NormalTok{(CovidDataPennTotal, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Age.Group, }\AttributeTok{y =}\NormalTok{ COVID.}\FloatTok{19.}\NormalTok{Deaths)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{colour =} \FunctionTok{factor}\NormalTok{(Sex)), }
             \AttributeTok{position =} \StringTok{"jitter"}\NormalTok{, }
             \AttributeTok{alpha =} \FloatTok{0.8}\NormalTok{,     }\CommentTok{\#Change transparency for aesthetics}
             \AttributeTok{size=}\FloatTok{1.0}\NormalTok{) }\SpecialCharTok{+}      \CommentTok{\#Change size for aesthetics}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x,}\AttributeTok{method=}\StringTok{\textquotesingle{}lm\textquotesingle{}}\NormalTok{,}\FunctionTok{aes}\NormalTok{(}\AttributeTok{group =} \FunctionTok{factor}\NormalTok{(Sex), }
                              \AttributeTok{colour =} \FunctionTok{factor}\NormalTok{(Sex))) }\SpecialCharTok{+} 
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"right"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{\textquotesingle{}Covid{-}19 Deaths by Age in Pennsylvania (Total) \textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x=} \StringTok{"Age Group"}\NormalTok{, }\AttributeTok{y=} \StringTok{"COVID{-}19 Deaths"}\NormalTok{, }\AttributeTok{color=} \StringTok{"Gender"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \DecValTok{1}\NormalTok{, }\AttributeTok{hjust=}\FloatTok{0.5}\NormalTok{))}
  \FunctionTok{theme\_cowplot}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## List of 93
##  $ line                      :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : num 1
##   ..$ lineend      : chr "butt"
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ rect                      :List of 5
##   ..$ fill         : logi NA
##   ..$ colour       : logi NA
##   ..$ size         : num 0.5
##   ..$ linetype     : num 1
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_rect" "element"
##  $ text                      :List of 11
##   ..$ family       : chr ""
##   ..$ face         : chr "plain"
##   ..$ colour       : chr "black"
##   ..$ size         : num 14
##   ..$ hjust        : num 0.5
##   ..$ vjust        : num 0.5
##   ..$ angle        : num 0
##   ..$ lineheight   : num 0.9
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ title                     : NULL
##  $ aspect.ratio              : NULL
##  $ axis.title                : NULL
##  $ axis.title.x              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3.5points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.x.top          :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 3.5points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.x.bottom       : NULL
##  $ axis.title.y              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : num 90
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 3.5points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.y.left         : NULL
##  $ axis.title.y.right        :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : num -90
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 3.5points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text                 :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : chr "black"
##   ..$ size         : num 12
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x.top           :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 3points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x.bottom        : NULL
##  $ axis.text.y               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 1
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 3points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.y.left          : NULL
##  $ axis.text.y.right         :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 3points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.ticks                :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : NULL
##   ..$ lineend      : NULL
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ axis.ticks.x              : NULL
##  $ axis.ticks.x.top          : NULL
##  $ axis.ticks.x.bottom       : NULL
##  $ axis.ticks.y              : NULL
##  $ axis.ticks.y.left         : NULL
##  $ axis.ticks.y.right        : NULL
##  $ axis.ticks.length         : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ axis.ticks.length.x       : NULL
##  $ axis.ticks.length.x.top   : NULL
##  $ axis.ticks.length.x.bottom: NULL
##  $ axis.ticks.length.y       : NULL
##  $ axis.ticks.length.y.left  : NULL
##  $ axis.ticks.length.y.right : NULL
##  $ axis.line                 :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : NULL
##   ..$ lineend      : chr "square"
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ axis.line.x               : NULL
##  $ axis.line.x.top           : NULL
##  $ axis.line.x.bottom        : NULL
##  $ axis.line.y               : NULL
##  $ axis.line.y.left          : NULL
##  $ axis.line.y.right         : NULL
##  $ legend.background         : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.margin             : 'margin' num [1:4] 0points 0points 0points 0points
##   ..- attr(*, "unit")= int 8
##  $ legend.spacing            : 'simpleUnit' num 14points
##   ..- attr(*, "unit")= int 8
##  $ legend.spacing.x          : NULL
##  $ legend.spacing.y          : NULL
##  $ legend.key                : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.key.size           : 'simpleUnit' num 15.4points
##   ..- attr(*, "unit")= int 8
##  $ legend.key.height         : NULL
##  $ legend.key.width          : NULL
##  $ legend.text               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ legend.text.align         : NULL
##  $ legend.title              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ legend.title.align        : NULL
##  $ legend.position           : chr "right"
##  $ legend.direction          : NULL
##  $ legend.justification      : chr [1:2] "left" "center"
##  $ legend.box                : NULL
##  $ legend.box.just           : NULL
##  $ legend.box.margin         : 'margin' num [1:4] 0points 0points 0points 0points
##   ..- attr(*, "unit")= int 8
##  $ legend.box.background     : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.box.spacing        : 'simpleUnit' num 14points
##   ..- attr(*, "unit")= int 8
##  $ panel.background          : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.border              : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.spacing             : 'simpleUnit' num 7points
##   ..- attr(*, "unit")= int 8
##  $ panel.spacing.x           : NULL
##  $ panel.spacing.y           : NULL
##  $ panel.grid                : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.grid.major          : NULL
##  $ panel.grid.minor          : NULL
##  $ panel.grid.major.x        : NULL
##  $ panel.grid.major.y        : NULL
##  $ panel.grid.minor.x        : NULL
##  $ panel.grid.minor.y        : NULL
##  $ panel.ontop               : logi FALSE
##  $ plot.background           : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ plot.title                :List of 11
##   ..$ family       : NULL
##   ..$ face         : chr "bold"
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 1.14
##   ..$ hjust        : num 0
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 7points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.title.position       : chr "panel"
##  $ plot.subtitle             :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : num 0
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 7points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.caption              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.786
##   ..$ hjust        : num 1
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 7points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.caption.position     : chr "panel"
##  $ plot.tag                  :List of 11
##   ..$ family       : NULL
##   ..$ face         : chr "bold"
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : num 0.7
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.tag.position         : num [1:2] 0 1
##  $ plot.margin               : 'margin' num [1:4] 7points 7points 7points 7points
##   ..- attr(*, "unit")= int 8
##  $ strip.background          :List of 5
##   ..$ fill         : chr "grey80"
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_rect" "element"
##  $ strip.background.x        : NULL
##  $ strip.background.y        : NULL
##  $ strip.placement           : chr "inside"
##  $ strip.text                :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3.5points 3.5points 3.5points 3.5points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ strip.text.x              : NULL
##  $ strip.text.y              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : num -90
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ strip.switch.pad.grid     : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ strip.switch.pad.wrap     : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ strip.text.y.left         :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : num 90
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  - attr(*, "class")= chr [1:2] "theme" "gg"
##  - attr(*, "complete")= logi TRUE
##  - attr(*, "validate")= logi TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(PennTotal)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 1 rows containing non-finite values (stat_smooth).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 1 rows containing missing values (geom_point).
\end{verbatim}

\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-22-1.pdf}

A great, refined, visualization was created! Lets take the same code
structure from the previous code chunk and look at COVID-19 Deaths from
Pennsylvania by month. The creation of a new data frame, filtering, and
creation of a new plot name should be applied. The next plot is a
manipulation of the x axis (change to Month) and factor (change to
Year). Of course, dress the plot up by changing plot titles.

One additional line of code, however, should be included to change the x
axis numeric categories (which represent the numeric month) to a
character (month name). This can be accomplished using the already
loaded package ``Stat2Data''. The command structure is as follows:
scale\_x\_continuous(breaks = seq\_along(month.name), labels =
month.name). This line changes the month observation of ``2'' to display
as February on the X axis.

(Line taken from
\url{https://stackoverflow.com/questions/69411847/changing-month-from-number-to-full-month-name-in-r})

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(Stat2Data)}
\NormalTok{CovidDataPennMonth}\OtherTok{\textless{}{-}}\FunctionTok{filter}\NormalTok{(PennData, Group}\SpecialCharTok{==}\StringTok{"By Month"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{==}\StringTok{"All Ages"}\NormalTok{)}
\NormalTok{PennMonth}\OtherTok{\textless{}{-}}\FunctionTok{ggplot}\NormalTok{(CovidDataPennMonth, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Month, }\AttributeTok{y =}\NormalTok{ COVID.}\FloatTok{19.}\NormalTok{Deaths)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{colour =} \FunctionTok{factor}\NormalTok{(Year)), }
             \AttributeTok{position =} \StringTok{"jitter"}\NormalTok{, }
             \AttributeTok{alpha =} \FloatTok{0.8}\NormalTok{,}
             \AttributeTok{size=}\FloatTok{0.05}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x,}\AttributeTok{method=}\StringTok{\textquotesingle{}lm\textquotesingle{}}\NormalTok{,}\FunctionTok{aes}\NormalTok{(}\AttributeTok{group =} \FunctionTok{factor}\NormalTok{(Year), }
                              \AttributeTok{colour =} \FunctionTok{factor}\NormalTok{(Year))) }\SpecialCharTok{+} 
  \FunctionTok{scale\_x\_continuous}\NormalTok{(}\AttributeTok{breaks =} \FunctionTok{seq\_along}\NormalTok{(month.name), }\AttributeTok{labels =}\NormalTok{ month.name) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"right"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{\textquotesingle{}Covid{-}19 Deaths by Month in Pennsylvania \textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x=} \StringTok{"Month"}\NormalTok{, }\AttributeTok{y=} \StringTok{"COVID{-}19 Deaths"}\NormalTok{, }\AttributeTok{color=}\StringTok{"Year"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \DecValTok{1}\NormalTok{, }\AttributeTok{hjust=}\FloatTok{0.5}\NormalTok{))}
  \FunctionTok{theme\_cowplot}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## List of 93
##  $ line                      :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : num 1
##   ..$ lineend      : chr "butt"
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ rect                      :List of 5
##   ..$ fill         : logi NA
##   ..$ colour       : logi NA
##   ..$ size         : num 0.5
##   ..$ linetype     : num 1
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_rect" "element"
##  $ text                      :List of 11
##   ..$ family       : chr ""
##   ..$ face         : chr "plain"
##   ..$ colour       : chr "black"
##   ..$ size         : num 14
##   ..$ hjust        : num 0.5
##   ..$ vjust        : num 0.5
##   ..$ angle        : num 0
##   ..$ lineheight   : num 0.9
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ title                     : NULL
##  $ aspect.ratio              : NULL
##  $ axis.title                : NULL
##  $ axis.title.x              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3.5points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.x.top          :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 3.5points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.x.bottom       : NULL
##  $ axis.title.y              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : num 90
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 3.5points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.y.left         : NULL
##  $ axis.title.y.right        :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : num -90
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 3.5points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text                 :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : chr "black"
##   ..$ size         : num 12
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x.top           :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 3points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x.bottom        : NULL
##  $ axis.text.y               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 1
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 3points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.y.left          : NULL
##  $ axis.text.y.right         :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 3points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.ticks                :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : NULL
##   ..$ lineend      : NULL
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ axis.ticks.x              : NULL
##  $ axis.ticks.x.top          : NULL
##  $ axis.ticks.x.bottom       : NULL
##  $ axis.ticks.y              : NULL
##  $ axis.ticks.y.left         : NULL
##  $ axis.ticks.y.right        : NULL
##  $ axis.ticks.length         : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ axis.ticks.length.x       : NULL
##  $ axis.ticks.length.x.top   : NULL
##  $ axis.ticks.length.x.bottom: NULL
##  $ axis.ticks.length.y       : NULL
##  $ axis.ticks.length.y.left  : NULL
##  $ axis.ticks.length.y.right : NULL
##  $ axis.line                 :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : NULL
##   ..$ lineend      : chr "square"
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ axis.line.x               : NULL
##  $ axis.line.x.top           : NULL
##  $ axis.line.x.bottom        : NULL
##  $ axis.line.y               : NULL
##  $ axis.line.y.left          : NULL
##  $ axis.line.y.right         : NULL
##  $ legend.background         : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.margin             : 'margin' num [1:4] 0points 0points 0points 0points
##   ..- attr(*, "unit")= int 8
##  $ legend.spacing            : 'simpleUnit' num 14points
##   ..- attr(*, "unit")= int 8
##  $ legend.spacing.x          : NULL
##  $ legend.spacing.y          : NULL
##  $ legend.key                : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.key.size           : 'simpleUnit' num 15.4points
##   ..- attr(*, "unit")= int 8
##  $ legend.key.height         : NULL
##  $ legend.key.width          : NULL
##  $ legend.text               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ legend.text.align         : NULL
##  $ legend.title              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ legend.title.align        : NULL
##  $ legend.position           : chr "right"
##  $ legend.direction          : NULL
##  $ legend.justification      : chr [1:2] "left" "center"
##  $ legend.box                : NULL
##  $ legend.box.just           : NULL
##  $ legend.box.margin         : 'margin' num [1:4] 0points 0points 0points 0points
##   ..- attr(*, "unit")= int 8
##  $ legend.box.background     : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.box.spacing        : 'simpleUnit' num 14points
##   ..- attr(*, "unit")= int 8
##  $ panel.background          : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.border              : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.spacing             : 'simpleUnit' num 7points
##   ..- attr(*, "unit")= int 8
##  $ panel.spacing.x           : NULL
##  $ panel.spacing.y           : NULL
##  $ panel.grid                : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.grid.major          : NULL
##  $ panel.grid.minor          : NULL
##  $ panel.grid.major.x        : NULL
##  $ panel.grid.major.y        : NULL
##  $ panel.grid.minor.x        : NULL
##  $ panel.grid.minor.y        : NULL
##  $ panel.ontop               : logi FALSE
##  $ plot.background           : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ plot.title                :List of 11
##   ..$ family       : NULL
##   ..$ face         : chr "bold"
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 1.14
##   ..$ hjust        : num 0
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 7points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.title.position       : chr "panel"
##  $ plot.subtitle             :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : num 0
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 7points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.caption              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.786
##   ..$ hjust        : num 1
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 7points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.caption.position     : chr "panel"
##  $ plot.tag                  :List of 11
##   ..$ family       : NULL
##   ..$ face         : chr "bold"
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : num 0.7
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.tag.position         : num [1:2] 0 1
##  $ plot.margin               : 'margin' num [1:4] 7points 7points 7points 7points
##   ..- attr(*, "unit")= int 8
##  $ strip.background          :List of 5
##   ..$ fill         : chr "grey80"
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_rect" "element"
##  $ strip.background.x        : NULL
##  $ strip.background.y        : NULL
##  $ strip.placement           : chr "inside"
##  $ strip.text                :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3.5points 3.5points 3.5points 3.5points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ strip.text.x              : NULL
##  $ strip.text.y              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : num -90
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ strip.switch.pad.grid     : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ strip.switch.pad.wrap     : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ strip.text.y.left         :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : num 90
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  - attr(*, "class")= chr [1:2] "theme" "gg"
##  - attr(*, "complete")= logi TRUE
##  - attr(*, "validate")= logi TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(PennMonth)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-23-1.pdf}

This is a neat visual. Notice how the year 2022 only has two months of
data collection. If statistical analysis were to be completed with this
graph, the year 2022 would likely be removed as no informative
comparison can be made using a variable that has incomplete data
collection.

We can also take a look at monthly COVID-19 deaths between Female/Males
in Pennsylvania. Again, the same formula of data visualization will be
utilized, however, this time we will try using boxplots and density
plots. Boxplots are a great graphing tool to apply to look for outlying
data. Density plots are beneficial for looking at the representation of
the distribution of a numeric variable.

Specify the geom\_ of the plots by inserting geom\_boxplot or
geom\_density into the code. Finally, theme\_cowplot() allows users to
plot the graphs in specified frames using the function: plot\_grid(name,
name, \ldots, ncol=\#).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PM1}\OtherTok{\textless{}{-}}\FunctionTok{ggplot}\NormalTok{(CovidDataPennMonth) }\SpecialCharTok{+}
  \FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Sex , }\AttributeTok{y=}\NormalTok{COVID.}\FloatTok{19.}\NormalTok{Deaths) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{width=}\NormalTok{.}\DecValTok{15}\NormalTok{, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{color=}\NormalTok{Sex)) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Monthly Covid{-}19 Death vs Sex In Pennsylvania"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x=}\StringTok{"Sex"}\NormalTok{, }\AttributeTok{y=}\StringTok{"COVID{-}19 Deaths"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_cowplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{0}\NormalTok{, }\AttributeTok{vjust =} \DecValTok{1}\NormalTok{, }\AttributeTok{hjust=}\FloatTok{0.5}\NormalTok{))}
  
\NormalTok{PM2}\OtherTok{\textless{}{-}}\FunctionTok{ggplot}\NormalTok{(CovidDataPennMonth) }\SpecialCharTok{+}
  \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ COVID.}\FloatTok{19.}\NormalTok{Deaths, }\AttributeTok{fill =}\NormalTok{ Sex) }\SpecialCharTok{+} 
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{alpha=}\NormalTok{.}\DecValTok{3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x=} \StringTok{"Deaths"}\NormalTok{, }\AttributeTok{y=}\StringTok{"Density"}\NormalTok{, }\AttributeTok{title=}\StringTok{"Density vs Monthly Covid{-}19 Deaths In Pennsylvania"}\NormalTok{)}
  \FunctionTok{theme\_cowplot}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## List of 93
##  $ line                      :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : num 1
##   ..$ lineend      : chr "butt"
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ rect                      :List of 5
##   ..$ fill         : logi NA
##   ..$ colour       : logi NA
##   ..$ size         : num 0.5
##   ..$ linetype     : num 1
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_rect" "element"
##  $ text                      :List of 11
##   ..$ family       : chr ""
##   ..$ face         : chr "plain"
##   ..$ colour       : chr "black"
##   ..$ size         : num 14
##   ..$ hjust        : num 0.5
##   ..$ vjust        : num 0.5
##   ..$ angle        : num 0
##   ..$ lineheight   : num 0.9
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ title                     : NULL
##  $ aspect.ratio              : NULL
##  $ axis.title                : NULL
##  $ axis.title.x              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3.5points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.x.top          :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 3.5points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.x.bottom       : NULL
##  $ axis.title.y              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : num 90
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 3.5points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.y.left         : NULL
##  $ axis.title.y.right        :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : num -90
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 3.5points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text                 :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : chr "black"
##   ..$ size         : num 12
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x.top           :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 3points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x.bottom        : NULL
##  $ axis.text.y               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 1
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 3points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.y.left          : NULL
##  $ axis.text.y.right         :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 3points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.ticks                :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : NULL
##   ..$ lineend      : NULL
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ axis.ticks.x              : NULL
##  $ axis.ticks.x.top          : NULL
##  $ axis.ticks.x.bottom       : NULL
##  $ axis.ticks.y              : NULL
##  $ axis.ticks.y.left         : NULL
##  $ axis.ticks.y.right        : NULL
##  $ axis.ticks.length         : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ axis.ticks.length.x       : NULL
##  $ axis.ticks.length.x.top   : NULL
##  $ axis.ticks.length.x.bottom: NULL
##  $ axis.ticks.length.y       : NULL
##  $ axis.ticks.length.y.left  : NULL
##  $ axis.ticks.length.y.right : NULL
##  $ axis.line                 :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : NULL
##   ..$ lineend      : chr "square"
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ axis.line.x               : NULL
##  $ axis.line.x.top           : NULL
##  $ axis.line.x.bottom        : NULL
##  $ axis.line.y               : NULL
##  $ axis.line.y.left          : NULL
##  $ axis.line.y.right         : NULL
##  $ legend.background         : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.margin             : 'margin' num [1:4] 0points 0points 0points 0points
##   ..- attr(*, "unit")= int 8
##  $ legend.spacing            : 'simpleUnit' num 14points
##   ..- attr(*, "unit")= int 8
##  $ legend.spacing.x          : NULL
##  $ legend.spacing.y          : NULL
##  $ legend.key                : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.key.size           : 'simpleUnit' num 15.4points
##   ..- attr(*, "unit")= int 8
##  $ legend.key.height         : NULL
##  $ legend.key.width          : NULL
##  $ legend.text               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ legend.text.align         : NULL
##  $ legend.title              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ legend.title.align        : NULL
##  $ legend.position           : chr "right"
##  $ legend.direction          : NULL
##  $ legend.justification      : chr [1:2] "left" "center"
##  $ legend.box                : NULL
##  $ legend.box.just           : NULL
##  $ legend.box.margin         : 'margin' num [1:4] 0points 0points 0points 0points
##   ..- attr(*, "unit")= int 8
##  $ legend.box.background     : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.box.spacing        : 'simpleUnit' num 14points
##   ..- attr(*, "unit")= int 8
##  $ panel.background          : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.border              : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.spacing             : 'simpleUnit' num 7points
##   ..- attr(*, "unit")= int 8
##  $ panel.spacing.x           : NULL
##  $ panel.spacing.y           : NULL
##  $ panel.grid                : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.grid.major          : NULL
##  $ panel.grid.minor          : NULL
##  $ panel.grid.major.x        : NULL
##  $ panel.grid.major.y        : NULL
##  $ panel.grid.minor.x        : NULL
##  $ panel.grid.minor.y        : NULL
##  $ panel.ontop               : logi FALSE
##  $ plot.background           : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ plot.title                :List of 11
##   ..$ family       : NULL
##   ..$ face         : chr "bold"
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 1.14
##   ..$ hjust        : num 0
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 7points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.title.position       : chr "panel"
##  $ plot.subtitle             :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : num 0
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 7points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.caption              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.786
##   ..$ hjust        : num 1
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 7points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.caption.position     : chr "panel"
##  $ plot.tag                  :List of 11
##   ..$ family       : NULL
##   ..$ face         : chr "bold"
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : num 0.7
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.tag.position         : num [1:2] 0 1
##  $ plot.margin               : 'margin' num [1:4] 7points 7points 7points 7points
##   ..- attr(*, "unit")= int 8
##  $ strip.background          :List of 5
##   ..$ fill         : chr "grey80"
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_rect" "element"
##  $ strip.background.x        : NULL
##  $ strip.background.y        : NULL
##  $ strip.placement           : chr "inside"
##  $ strip.text                :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3.5points 3.5points 3.5points 3.5points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ strip.text.x              : NULL
##  $ strip.text.y              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : num -90
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ strip.switch.pad.grid     : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ strip.switch.pad.wrap     : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ strip.text.y.left         :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : num 90
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  - attr(*, "class")= chr [1:2] "theme" "gg"
##  - attr(*, "complete")= logi TRUE
##  - attr(*, "validate")= logi TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_grid}\NormalTok{(PM1,PM2, }\AttributeTok{ncol=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-24-1.pdf}

Finally, lets plot COVID-19 Deaths from Pennsylvania by year.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CovidDataPennYear}\OtherTok{\textless{}{-}}\FunctionTok{filter}\NormalTok{(PennData, Group}\SpecialCharTok{==}\StringTok{"By Year"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{==}\StringTok{"All Ages"}\NormalTok{)}
\NormalTok{PennYear}\OtherTok{\textless{}{-}}\FunctionTok{ggplot}\NormalTok{(CovidDataPennYear, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Year, }\AttributeTok{y =}\NormalTok{ COVID.}\FloatTok{19.}\NormalTok{Deaths)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{colour =} \FunctionTok{factor}\NormalTok{(Sex)), }
             \AttributeTok{position =} \StringTok{"jitter"}\NormalTok{, }
             \AttributeTok{alpha =} \FloatTok{0.8}\NormalTok{,}
             \AttributeTok{size=}\FloatTok{0.05}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x,}\AttributeTok{method=}\StringTok{\textquotesingle{}lm\textquotesingle{}}\NormalTok{,}\FunctionTok{aes}\NormalTok{(}\AttributeTok{group =} \FunctionTok{factor}\NormalTok{(Sex), }
                              \AttributeTok{colour =} \FunctionTok{factor}\NormalTok{(Sex))) }\SpecialCharTok{+} 
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"right"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{\textquotesingle{}Covid{-}19 Deaths by Month in Pennsylvania \textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x=} \StringTok{"Year"}\NormalTok{, }\AttributeTok{y=} \StringTok{"COVID{-}19 Deaths"}\NormalTok{, }\AttributeTok{color=}\StringTok{"Gender"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \DecValTok{1}\NormalTok{, }\AttributeTok{hjust=}\FloatTok{0.5}\NormalTok{))}
  \FunctionTok{theme\_cowplot}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## List of 93
##  $ line                      :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : num 1
##   ..$ lineend      : chr "butt"
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ rect                      :List of 5
##   ..$ fill         : logi NA
##   ..$ colour       : logi NA
##   ..$ size         : num 0.5
##   ..$ linetype     : num 1
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_rect" "element"
##  $ text                      :List of 11
##   ..$ family       : chr ""
##   ..$ face         : chr "plain"
##   ..$ colour       : chr "black"
##   ..$ size         : num 14
##   ..$ hjust        : num 0.5
##   ..$ vjust        : num 0.5
##   ..$ angle        : num 0
##   ..$ lineheight   : num 0.9
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ title                     : NULL
##  $ aspect.ratio              : NULL
##  $ axis.title                : NULL
##  $ axis.title.x              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3.5points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.x.top          :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 3.5points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.x.bottom       : NULL
##  $ axis.title.y              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : num 90
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 3.5points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.title.y.left         : NULL
##  $ axis.title.y.right        :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : num -90
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 3.5points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text                 :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : chr "black"
##   ..$ size         : num 12
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x.top           :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 3points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.x.bottom        : NULL
##  $ axis.text.y               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 1
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 3points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.text.y.left          : NULL
##  $ axis.text.y.right         :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 0points 3points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ axis.ticks                :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : NULL
##   ..$ lineend      : NULL
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ axis.ticks.x              : NULL
##  $ axis.ticks.x.top          : NULL
##  $ axis.ticks.x.bottom       : NULL
##  $ axis.ticks.y              : NULL
##  $ axis.ticks.y.left         : NULL
##  $ axis.ticks.y.right        : NULL
##  $ axis.ticks.length         : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ axis.ticks.length.x       : NULL
##  $ axis.ticks.length.x.top   : NULL
##  $ axis.ticks.length.x.bottom: NULL
##  $ axis.ticks.length.y       : NULL
##  $ axis.ticks.length.y.left  : NULL
##  $ axis.ticks.length.y.right : NULL
##  $ axis.line                 :List of 6
##   ..$ colour       : chr "black"
##   ..$ size         : num 0.5
##   ..$ linetype     : NULL
##   ..$ lineend      : chr "square"
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_line" "element"
##  $ axis.line.x               : NULL
##  $ axis.line.x.top           : NULL
##  $ axis.line.x.bottom        : NULL
##  $ axis.line.y               : NULL
##  $ axis.line.y.left          : NULL
##  $ axis.line.y.right         : NULL
##  $ legend.background         : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.margin             : 'margin' num [1:4] 0points 0points 0points 0points
##   ..- attr(*, "unit")= int 8
##  $ legend.spacing            : 'simpleUnit' num 14points
##   ..- attr(*, "unit")= int 8
##  $ legend.spacing.x          : NULL
##  $ legend.spacing.y          : NULL
##  $ legend.key                : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.key.size           : 'simpleUnit' num 15.4points
##   ..- attr(*, "unit")= int 8
##  $ legend.key.height         : NULL
##  $ legend.key.width          : NULL
##  $ legend.text               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ legend.text.align         : NULL
##  $ legend.title              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ legend.title.align        : NULL
##  $ legend.position           : chr "right"
##  $ legend.direction          : NULL
##  $ legend.justification      : chr [1:2] "left" "center"
##  $ legend.box                : NULL
##  $ legend.box.just           : NULL
##  $ legend.box.margin         : 'margin' num [1:4] 0points 0points 0points 0points
##   ..- attr(*, "unit")= int 8
##  $ legend.box.background     : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ legend.box.spacing        : 'simpleUnit' num 14points
##   ..- attr(*, "unit")= int 8
##  $ panel.background          : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.border              : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.spacing             : 'simpleUnit' num 7points
##   ..- attr(*, "unit")= int 8
##  $ panel.spacing.x           : NULL
##  $ panel.spacing.y           : NULL
##  $ panel.grid                : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ panel.grid.major          : NULL
##  $ panel.grid.minor          : NULL
##  $ panel.grid.major.x        : NULL
##  $ panel.grid.major.y        : NULL
##  $ panel.grid.minor.x        : NULL
##  $ panel.grid.minor.y        : NULL
##  $ panel.ontop               : logi FALSE
##  $ plot.background           : list()
##   ..- attr(*, "class")= chr [1:2] "element_blank" "element"
##  $ plot.title                :List of 11
##   ..$ family       : NULL
##   ..$ face         : chr "bold"
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 1.14
##   ..$ hjust        : num 0
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 7points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.title.position       : chr "panel"
##  $ plot.subtitle             :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : num 0
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 0points 0points 7points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.caption              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.786
##   ..$ hjust        : num 1
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 7points 0points 0points 0points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.caption.position     : chr "panel"
##  $ plot.tag                  :List of 11
##   ..$ family       : NULL
##   ..$ face         : chr "bold"
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : num 0.7
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ plot.tag.position         : num [1:2] 0 1
##  $ plot.margin               : 'margin' num [1:4] 7points 7points 7points 7points
##   ..- attr(*, "unit")= int 8
##  $ strip.background          :List of 5
##   ..$ fill         : chr "grey80"
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_rect" "element"
##  $ strip.background.x        : NULL
##  $ strip.background.y        : NULL
##  $ strip.placement           : chr "inside"
##  $ strip.text                :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : 'rel' num 0.857
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : 'margin' num [1:4] 3.5points 3.5points 3.5points 3.5points
##   .. ..- attr(*, "unit")= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ strip.text.x              : NULL
##  $ strip.text.y              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : num -90
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  $ strip.switch.pad.grid     : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ strip.switch.pad.wrap     : 'simpleUnit' num 3.5points
##   ..- attr(*, "unit")= int 8
##  $ strip.text.y.left         :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : num 90
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, "class")= chr [1:2] "element_text" "element"
##  - attr(*, "class")= chr [1:2] "theme" "gg"
##  - attr(*, "complete")= logi TRUE
##  - attr(*, "validate")= logi TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(PennYear)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-25-1.pdf}

\#STATISTICAL ANALYSIS:

As a reminder, the hypotheses we are interested in for this R tutorial
are: 1. We hypothesize that there will be more COVID-19 deaths reported
for the East coast. 2. We hypothesize that there will be more COVID-19
deaths reported for older individuals in all states across the US. 3. We
hypothesize that there will be no difference in COVID-19 deaths between
the to genders in the US.

In order to test these hypotheses, we will be creating linear models
working solely with total deaths, or the ``By Total'' level of the
``Group'' column. This will allow is to avoid having to run a
statistical analysis on a time series, which is something we are not
covering in this tutorial.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  We hypothesize that there will be more COVID-19 deaths reported for
  the East coast.
\end{enumerate}

The first linear model we will be running will be used to determine if
the total number of Covid-19 deaths on the East Coast is significantly
different from those on the West Coast. The output of the linear model
function will be used to explain the statistical analysis, but for now
just follow along with the basic code format for a linear model:

lm(Response/Dependent Variable \textasciitilde{} Predictor/Independent
Variable, data=data.frame)

Notice that the product of this function is assigned the identity
``lmEvsW'' for East vs.~West Coast. This analysis is performed using the
lmCovidDataCoasts dataset, with all sex, by total, All Age observations,
excluding the ``States'' of ``United States'', ``New York City'', and
``Peurto Rico''. The 51 observations are present within the data frame
are explained by 1 per ``state'' for 51 ``states'' (the traditional 50
states + the District of Columbia). The summary(lmEvsW) plot(lmEvsW)
functions should always be ran in tandem with the execution of a linear
model in order to ensure the model can be assessed. Briefly look at the
output below after running the code chunk, and then follow the text
below the output describing the results of a linear model.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lmCovidDataCoasts}\OtherTok{\textless{}{-}}\FunctionTok{filter}\NormalTok{(Covid\_19, Group}\SpecialCharTok{==}\StringTok{"By Total"} \SpecialCharTok{\&}\NormalTok{ Sex}\SpecialCharTok{==}\StringTok{"All Sexes"} \SpecialCharTok{\&}\NormalTok{ Age.Group}\SpecialCharTok{==}\StringTok{"All Ages"} \SpecialCharTok{\&}\NormalTok{ State}\SpecialCharTok{!=}\StringTok{"United States"} \SpecialCharTok{\&}\NormalTok{ State}\SpecialCharTok{!=}\StringTok{"Puerto Rico"}\NormalTok{, State}\SpecialCharTok{!=} \StringTok{"New York City"}\NormalTok{ )}
\NormalTok{lmEvsW }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(COVID.}\FloatTok{19.}\NormalTok{Deaths }\SpecialCharTok{\textasciitilde{}}\NormalTok{ WC, }\AttributeTok{data=}\NormalTok{lmCovidDataCoasts)}
\FunctionTok{summary}\NormalTok{(lmEvsW)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = COVID.19.Deaths ~ WC, data = lmCovidDataCoasts)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -16349 -12674  -5230   5274  68391 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  16850.2     3284.6   5.130 4.95e-06 ***
## WCTRUE         303.8     5528.9   0.055    0.956    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 18870 on 49 degrees of freedom
## Multiple R-squared:  6.162e-05,  Adjusted R-squared:  -0.02035 
## F-statistic: 0.00302 on 1 and 49 DF,  p-value: 0.9564
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(lmEvsW)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-26-1.pdf}
\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-26-2.pdf}
\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-26-3.pdf}
\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-26-4.pdf}

The assumptions required to perform a linear model include the
following: i) Linearity: The relationship between X and the mean of Y is
linear, or the X variable is categorical. In this case, we are comparing
East Coast vs West Coast binomial categories, so we don't have to check
for linearity. In fact, we are only going to be analyzing categorical X
variables for the remainder of this tutorial, so this constraint is not
relevant to our analysis.

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{1}
\item
  Homoscedasticity: The variance of the residuals is random for each X
  value. Select the second output frame above. Because we are looking at
  a categorical variable, our X values become these 2 categories (east
  and west coast). Notice that the distribution of residuals is fairly
  consistent across both X values.
\item
  Independence: Observations are independent of each other. We can
  determine from intuition that the number of Covid-19 deaths are not
  dependent on the State name. It is still possible that State may have
  an effect on Covid-19 deaths, but this is different than ``state''
  being dependent on Covid-19 deaths.
\item
  Normality: For any fixed value of X, Y is normally distributed. Select
  the 3rd output frame. This can be evaluated from a qqplot, which you
  likely remember from your statistics course. If the points are
  distributed along the line, then the Y values are normally distributed
  for each X value.
\end{enumerate}

Notice that we do not have normal distribution for this analysis. This
does not make our linear model entirely not compatible with the data,
but does require that we interpret the results with caution.

Interpreting Significance: Select the first output frame above.
Theoretically what this linear model is doing is fitting a horizontal
line through the weighted mean Y value for one category of X (call this
X1). Then, the linear model is comparing the weighted mean Y value for
X1 to the weighted mean Y value of category X2 and determining the
probability (p value) that these two weighted mean values come from the
same population. A linear model is capable of comparing a number of
categorical variables like this, making it very useful.

Look under the ``Coefficients'' detection of output frame 1.
``(Intercept)'' shows the baseline X value that the rest are being
compared to. RStudio automatically selects the baseline category for
comparison by alphabetical order. Although it is not explicitly stated,
this category above is ``WCFALSE'', and WCTRUE is being compared to this
baseline. The number under the ``Estimate'' column for ``(Intercept)''
represents the the weighted average number of deaths per East Coast (or
WCFALSE) State, which in this case is 16850.2 deaths.

Now, looking at the WCTRUE row of code, notice the number under the
``Estimate'' column is 303.8 deaths. Remember, everything is in
comparison to the baseline category (WCFALSE), so this is actually
saying that states on the west coast have weighted average number of
deaths per state that is higher by 303.8 deaths. However, by looking
under the ``Pr(\textgreater\textbar t\textbar)'' (or p value) column in
the WCTRUE row, we can see that this difference in weighted average is
no where near close to being significant (p=0.956), and we can conclude
that the number of Covid-19 deaths do not differ significantly by coast.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  We hypothesize that there will be more COVID-19 deaths reported for
  older individuals in all states across the US.
\end{enumerate}

Run the following code chunk and see if you can follow along with the
code output. However, refer the the following hints before: - Extensive
filtering was done to compensate for NA values in the dataset. Do not
focus on this process to much. - Age ranges (years) 25-34, 35-44, 45-54,
55-64, and 65-74, 75-84, and 85 and over are included in the analysis -
Determine what constraints/assumptions a linear model makes is violated
- The baseline (``intercept'') age that the deaths at each age are being
compared to is the age range 25-34 years - Your should be able to see
that 4 of the 7 compared age ranges show a significant difference - Make
a conclusion to the hypothesis written above

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Covid\_19}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{ (State }\SpecialCharTok{!=} \StringTok{"United States"} \SpecialCharTok{\&}\NormalTok{ State }\SpecialCharTok{!=} \StringTok{"District of Columbia"} \SpecialCharTok{\&}\NormalTok{ State }\SpecialCharTok{!=} \StringTok{"New York City"} \SpecialCharTok{\&}\NormalTok{ State }\SpecialCharTok{!=} \StringTok{"Puerto Rico"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Group }\SpecialCharTok{==} \StringTok{"By Total"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Sex }\SpecialCharTok{==} \StringTok{"All Sexes"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{((Age.Group }\SpecialCharTok{!=} \StringTok{"0{-}17 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group }\SpecialCharTok{!=} \StringTok{"All Ages"} \SpecialCharTok{\&}\NormalTok{ Age.Group }\SpecialCharTok{!=} \StringTok{"50{-}64 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group }\SpecialCharTok{!=} \StringTok{"Under 1 year"} \SpecialCharTok{\&}\NormalTok{ Age.Group }\SpecialCharTok{!=} \StringTok{"1{-}4 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group }\SpecialCharTok{!=} \StringTok{"5{-}14 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group }\SpecialCharTok{!=} \StringTok{"18{-}29 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group }\SpecialCharTok{!=} \StringTok{"30{-}39 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group }\SpecialCharTok{!=} \StringTok{"40{-}49 years"} \SpecialCharTok{\&}\NormalTok{ Age.Group }\SpecialCharTok{!=} \StringTok{"15{-}24 years"}\NormalTok{))}\OtherTok{{-}\textgreater{}}\NormalTok{Covid\_19.State.Deaths.Age}

\NormalTok{lmOvsY }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(COVID.}\FloatTok{19.}\NormalTok{Deaths }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Age.Group, }\AttributeTok{data=}\NormalTok{Covid\_19.State.Deaths.Age)}
\FunctionTok{summary}\NormalTok{(lmOvsY)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = COVID.19.Deaths ~ Age.Group, data = Covid_19.State.Deaths.Age)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4297.8 -1460.7  -258.3   230.6 16421.2 
## 
## Coefficients:
##                            Estimate Std. Error t value Pr(>|t|)    
## (Intercept)                   193.1      456.5   0.423 0.672610    
## Age.Group35-44 years          291.8      645.6   0.452 0.651603    
## Age.Group45-54 years          972.7      645.6   1.507 0.132826    
## Age.Group55-64 years         2340.0      645.6   3.624 0.000334 ***
## Age.Group65-74 years         3745.8      645.6   5.802 1.49e-08 ***
## Age.Group75-84 years         4240.7      645.6   6.568 1.89e-10 ***
## Age.Group85 years and over   4264.2      645.6   6.605 1.52e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3228 on 343 degrees of freedom
## Multiple R-squared:  0.2253, Adjusted R-squared:  0.2118 
## F-statistic: 16.63 on 6 and 343 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(lmOvsY)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-27-1.pdf}
\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-27-2.pdf}

\begin{verbatim}
## hat values (leverages) are all = 0.02
##  and there are no factor predictors; no plot no. 5
\end{verbatim}

\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-27-3.pdf}
\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-27-4.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  We hypothesize that there will be no difference in COVID-19 deaths
  between the to genders in the US
\end{enumerate}

Run the code directly below this text:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Covid\_19}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{ (State }\SpecialCharTok{!=} \StringTok{"United States"} \SpecialCharTok{\&}\NormalTok{ State }\SpecialCharTok{!=} \StringTok{"District of Columbia"} \SpecialCharTok{\&}\NormalTok{ State }\SpecialCharTok{!=} \StringTok{"New York City"} \SpecialCharTok{\&}\NormalTok{ State }\SpecialCharTok{!=} \StringTok{"Puerto Rico"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Group }\SpecialCharTok{==} \StringTok{"By Total"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Sex }\SpecialCharTok{!=} \StringTok{"All Sexes"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{((Age.Group }\SpecialCharTok{==} \StringTok{"All Ages"}\NormalTok{))}\OtherTok{{-}\textgreater{}}\NormalTok{Covid\_19.State.Deaths.Sex}
\end{Highlighting}
\end{Shaded}

This code has created a data frame titled
``Covid\_19.State.Deaths.Sex'', containing cumulative data on the total
number of deaths since the beginning of the pandemic. In addition, these
deaths are further broken down by state and sex (male and female are
separate). Study the data frame, and then attempt to run a linear model
below investigating if the number of Covid-19 deaths in the US is
dependent on Sex. Use the following functions:

lm.name\textless-lm(response.variable \textasciitilde{}
predictor.variable, data=data.set.name) summary(lm.name) plot(lm.name)

For the correct code, see after the acknowledgement section below.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#type here}
\end{Highlighting}
\end{Shaded}

Follow up questions to consider: - What assumptions were violated? - Was
there a significant difference between the death of male and females? -
Make a conclusion about our hypothesis \#3 from this output

\hypertarget{target-audience}{%
\subsection{Target Audience}\label{target-audience}}

Upper level epidemiology class using R Studio for the first time.

\hypertarget{grading}{%
\subsection{Grading}\label{grading}}

Each student will be expected to complete the following tasks to earn
85\% of the points available for this assignment (21/25).

\begin{itemize}
\tightlist
\item
  Identify and obtain suitable dataset
\item
  Use a Github repository and version control to collaborate on the
  project
\item
  Spend 4-6 hours preparing, coding, and testing tutorial

  \begin{itemize}
  \tightlist
  \item
    Data exploration
  \item
    Data visualization
  \item
    Hypothesis testing
  \end{itemize}
\item
  Present tutorial in class
\item
  Provide public archive suitable for sharing to students/faculty
\end{itemize}

Tutorials from previous classes can be viewed at our public github site:
\url{https://github.com/Bucknell-Biol364}

Additional credit will be awarded for providing assistance to other
groups and for the development of a tutorial that goes beyond the
minimal expectations listed above.

\hypertarget{acknowledgements}{%
\section{Acknowledgements}\label{acknowledgements}}

Outline: README(Maisy) 1) Introduction to class (Ashley) 2) Introduction
to R (Maisy) Define RMD vs Regular R Loading Data Set Load Packages
Refer to glossary for a function/stats overview\ldots{} 3) Explore Data
Set (with function explanations) (Ashley) Formulate a question Read data
Check packaging Run structure Look at top and bottom of data Check your
n's 4) Visualize Data Set 1. Timeline vs death (Maisy) 2. Rank net
deaths by state (Ben) 3. Do older people have higher death rates than
younger (Ben) 4. West coast vs east coast (Ashley) 5. Covid-19 Deaths in
Pennsylvania (Ashley) 5) Statistical analysis to answer hypothesis (Ben)
1. We hypothesize that there will be more COVID-19 deaths reported for
the East coast. 2. We hypothesize that there will be more COVID-19
deaths reported for older individuals in all states across the US. 3. We
hypothesize that there will be no difference in COVID-19 deaths between
the to genders in the US.

Solution code to final linear model:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lmCDM1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(COVID.}\FloatTok{19.}\NormalTok{Deaths }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Sex, }\AttributeTok{data=}\NormalTok{Covid\_19.State.Deaths.Sex)}
\FunctionTok{summary}\NormalTok{(lmCDM1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = COVID.19.Deaths ~ Sex, data = Covid_19.State.Deaths.Sex)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -9268  -6208  -2484   2572  40962 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)     7728       1341   5.762 9.62e-08 ***
## SexMale         1806       1897   0.952    0.343    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 9484 on 98 degrees of freedom
## Multiple R-squared:  0.009164,   Adjusted R-squared:  -0.0009462 
## F-statistic: 0.9064 on 1 and 98 DF,  p-value: 0.3434
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(lmCDM1)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-30-1.pdf}
\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-30-2.pdf}

\begin{verbatim}
## hat values (leverages) are all = 0.02
##  and there are no factor predictors; no plot no. 5
\end{verbatim}

\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-30-3.pdf}
\includegraphics{Project01.FINAL_files/figure-latex/unnamed-chunk-30-4.pdf}

\end{document}
